providers = ["node"]

[phases.setup]
nixPkgs = ["git", "curl", "zip", "gnutar", "nginx", "nodejs", "gettext", "jq"]
paths = ["/usr/local/go/bin"]

[phases.build]
cmds = [
    "npm install",
    "npm run setup:wasm",
    "npm run build:wasm",
    "npm run setup:installables",
    "npm run build",
    "npm run validate:dist",
]

[start]
# TODO: replace simple node server with something better
cmd = "npm start"
