[phases.setup]
nixPkgs = ["go", "git", "python3"]
cmds = [
    "cd kobopatch-wasm && bash setup.sh",
    "cd kobopatch-wasm && bash build.sh",
]

[start]
cmd = "python3 -m http.server ${PORT:-8080} -d web/public"
