providers = ["node"]

[phases.setup]
nixPkgs = ["git", "curl", "zip", "gnutar", "nginx"]
paths = ["/usr/local/go/bin"]

[phases.build]
cmds = [
    "cd kobopatch-wasm && bash setup.sh",
    "cd kobopatch-wasm && bash build.sh",
    "cd nickelmenu && bash setup.sh",
    "cd web && npm install && npm run build",
]

[start]
cmd = "envsubst '${PORT}' < nginx.conf.template > /tmp/nginx.conf && exec nginx -c /tmp/nginx.conf -g 'daemon off;'"
