/**
 * catalogue.js — the ebook-fonts collection shipped by "Install additional fonts".
 *
 * GENERATED by tools/installables/generate-font-catalogue.mjs from the pinned
 * ebook-fonts archives (v2026.08.05) — do not edit by hand. Regenerate with
 * `npm run update:installables` (or run the generator directly) after the
 * archives change.
 *
 * Each family lists the exact .ttf files inside the collection archive, which
 * are also the file names installed into fonts/ on the device. A family's
 * on-device display name is "KF " + its name (the fonts' internal family name).
 */

export const FONT_COLLECTIONS = [
    {
        id: 'core',
        title: 'Core fonts',
        installable: 'ebook-fonts-core',
        asset: 'kobo-core-fonts.zip',
    },
    {
        id: 'extra',
        title: 'Extra fonts',
        installable: 'ebook-fonts-extra',
        asset: 'kobo-extra-fonts.zip',
    },
];

export const FONT_FAMILIES = [
    {
        id: 'bitter',
        name: 'Bitter',
        collection: 'core',
        files: ['KF_Bitter-Regular.ttf', 'KF_Bitter-Italic.ttf', 'KF_Bitter-Bold.ttf', 'KF_Bitter-BoldItalic.ttf'],
    },
    {
        id: 'cartisse',
        name: 'Cartisse',
        collection: 'core',
        files: ['KF_Cartisse-Regular.ttf', 'KF_Cartisse-Italic.ttf', 'KF_Cartisse-Bold.ttf', 'KF_Cartisse-BoldItalic.ttf'],
    },
    {
        id: 'charis',
        name: 'Charis',
        collection: 'core',
        files: ['KF_Charis-Regular.ttf', 'KF_Charis-Italic.ttf', 'KF_Charis-Bold.ttf', 'KF_Charis-BoldItalic.ttf'],
    },
    {
        id: 'garamond',
        name: 'Garamond',
        collection: 'core',
        files: ['KF_Garamond-Regular.ttf', 'KF_Garamond-Italic.ttf', 'KF_Garamond-Bold.ttf', 'KF_Garamond-BoldItalic.ttf'],
    },
    {
        id: 'jost',
        name: 'Jost',
        collection: 'core',
        files: ['KF_Jost-Regular.ttf', 'KF_Jost-Italic.ttf', 'KF_Jost-Bold.ttf', 'KF_Jost-BoldItalic.ttf'],
    },
    {
        id: 'legible-next',
        name: 'Legible Next',
        collection: 'core',
        files: ['KF_Legible_Next-Regular.ttf', 'KF_Legible_Next-Italic.ttf', 'KF_Legible_Next-Bold.ttf', 'KF_Legible_Next-BoldItalic.ttf'],
    },
    {
        id: 'libron',
        name: 'Libron',
        collection: 'core',
        files: ['KF_Libron-Regular.ttf', 'KF_Libron-Italic.ttf', 'KF_Libron-Bold.ttf', 'KF_Libron-BoldItalic.ttf'],
    },
    {
        id: 'palatium',
        name: 'Palatium',
        collection: 'core',
        files: ['KF_Palatium-Regular.ttf', 'KF_Palatium-Italic.ttf', 'KF_Palatium-Bold.ttf', 'KF_Palatium-BoldItalic.ttf'],
    },
    {
        id: 'sourcerer',
        name: 'Sourcerer',
        collection: 'core',
        files: ['KF_Sourcerer-Regular.ttf', 'KF_Sourcerer-Italic.ttf', 'KF_Sourcerer-Bold.ttf', 'KF_Sourcerer-BoldItalic.ttf'],
    },
    {
        id: 'adelph',
        name: 'Adelph',
        collection: 'extra',
        files: ['KF_Adelph-Regular.ttf', 'KF_Adelph-Italic.ttf', 'KF_Adelph-Bold.ttf', 'KF_Adelph-BoldItalic.ttf'],
    },
    {
        id: 'alegreya',
        name: 'Alegreya',
        collection: 'extra',
        files: ['KF_Alegreya-Regular.ttf', 'KF_Alegreya-Italic.ttf', 'KF_Alegreya-Bold.ttf', 'KF_Alegreya-BoldItalic.ttf'],
    },
    {
        id: 'alizar',
        name: 'Alizar',
        collection: 'extra',
        files: ['KF_Alizar-Regular.ttf', 'KF_Alizar-Italic.ttf', 'KF_Alizar-Bold.ttf', 'KF_Alizar-BoldItalic.ttf'],
    },
    {
        id: 'ancizar-sans',
        name: 'Ancizar Sans',
        collection: 'extra',
        files: ['KF_Ancizar_Sans-Regular.ttf', 'KF_Ancizar_Sans-Italic.ttf', 'KF_Ancizar_Sans-Bold.ttf', 'KF_Ancizar_Sans-BoldItalic.ttf'],
    },
    {
        id: 'ancizar-serif',
        name: 'Ancizar Serif',
        collection: 'extra',
        files: ['KF_Ancizar_Serif-Regular.ttf', 'KF_Ancizar_Serif-Italic.ttf', 'KF_Ancizar_Serif-Bold.ttf', 'KF_Ancizar_Serif-BoldItalic.ttf'],
    },
    {
        id: 'andada',
        name: 'Andada',
        collection: 'extra',
        files: ['KF_Andada-Regular.ttf', 'KF_Andada-Italic.ttf', 'KF_Andada-Bold.ttf', 'KF_Andada-BoldItalic.ttf'],
    },
    {
        id: 'basker',
        name: 'Basker',
        collection: 'extra',
        files: ['KF_Basker-Regular.ttf', 'KF_Basker-Italic.ttf', 'KF_Basker-Bold.ttf', 'KF_Basker-BoldItalic.ttf'],
    },
    {
        id: 'cardo',
        name: 'Cardo',
        collection: 'extra',
        files: ['KF_Cardo-Regular.ttf', 'KF_Cardo-Italic.ttf', 'KF_Cardo-Bold.ttf'],
    },
    {
        id: 'castoro',
        name: 'Castoro',
        collection: 'extra',
        files: ['KF_Castoro-Regular.ttf', 'KF_Castoro-Italic.ttf', 'KF_Castoro-Bold.ttf', 'KF_Castoro-BoldItalic.ttf'],
    },
    {
        id: 'charis-literacy',
        name: 'Charis Literacy',
        collection: 'extra',
        files: ['KF_Charis_Literacy-Regular.ttf', 'KF_Charis_Literacy-Italic.ttf', 'KF_Charis_Literacy-Bold.ttf', 'KF_Charis_Literacy-BoldItalic.ttf'],
    },
    {
        id: 'charis-old-style',
        name: 'Charis Old Style',
        collection: 'extra',
        files: ['KF_Charis_Old_Style-Regular.ttf', 'KF_Charis_Old_Style-Italic.ttf', 'KF_Charis_Old_Style-Bold.ttf', 'KF_Charis_Old_Style-BoldItalic.ttf'],
    },
    {
        id: 'clara',
        name: 'Clara',
        collection: 'extra',
        files: ['KF_Clara-Regular.ttf', 'KF_Clara-Italic.ttf', 'KF_Clara-Bold.ttf', 'KF_Clara-BoldItalic.ttf'],
    },
    {
        id: 'disleksio',
        name: 'Disleksio',
        collection: 'extra',
        files: ['KF_Disleksio-Regular.ttf', 'KF_Disleksio-Italic.ttf', 'KF_Disleksio-Bold.ttf', 'KF_Disleksio-BoldItalic.ttf'],
    },
    {
        id: 'elstob',
        name: 'Elstob',
        collection: 'extra',
        files: ['KF_Elstob-Regular.ttf', 'KF_Elstob-Italic.ttf', 'KF_Elstob-Bold.ttf', 'KF_Elstob-BoldItalic.ttf'],
    },
    {
        id: 'erewhon',
        name: 'Erewhon',
        collection: 'extra',
        files: ['KF_Erewhon-Regular.ttf', 'KF_Erewhon-Italic.ttf', 'KF_Erewhon-Bold.ttf', 'KF_Erewhon-BoldItalic.ttf'],
    },
    {
        id: 'gentium',
        name: 'Gentium',
        collection: 'extra',
        files: ['KF_Gentium-Regular.ttf', 'KF_Gentium-Italic.ttf', 'KF_Gentium-Bold.ttf', 'KF_Gentium-BoldItalic.ttf'],
    },
    {
        id: 'georsio',
        name: 'Georsio',
        collection: 'extra',
        files: ['KF_Georsio-Regular.ttf', 'KF_Georsio-Italic.ttf', 'KF_Georsio-Bold.ttf', 'KF_Georsio-BoldItalic.ttf'],
    },
    {
        id: 'halcyon',
        name: 'Halcyon',
        collection: 'extra',
        files: ['KF_Halcyon-Regular.ttf', 'KF_Halcyon-Italic.ttf', 'KF_Halcyon-Bold.ttf', 'KF_Halcyon-BoldItalic.ttf'],
    },
    {
        id: 'ibarra',
        name: 'Ibarra',
        collection: 'extra',
        files: ['KF_Ibarra-Regular.ttf', 'KF_Ibarra-Italic.ttf', 'KF_Ibarra-Bold.ttf', 'KF_Ibarra-BoldItalic.ttf'],
    },
    {
        id: 'junius',
        name: 'Junius',
        collection: 'extra',
        files: ['KF_Junius-Regular.ttf', 'KF_Junius-Italic.ttf', 'KF_Junius-Bold.ttf', 'KF_Junius-BoldItalic.ttf'],
    },
    {
        id: 'kierkegaard',
        name: 'Kierkegaard',
        collection: 'extra',
        files: ['KF_Kierkegaard-Regular.ttf', 'KF_Kierkegaard-Italic.ttf', 'KF_Kierkegaard-Bold.ttf', 'KF_Kierkegaard-BoldItalic.ttf'],
    },
    {
        id: 'libertinus',
        name: 'Libertinus',
        collection: 'extra',
        files: ['KF_Libertinus-Regular.ttf', 'KF_Libertinus-Italic.ttf', 'KF_Libertinus-Bold.ttf', 'KF_Libertinus-BoldItalic.ttf'],
    },
    {
        id: 'literata',
        name: 'Literata',
        collection: 'extra',
        files: ['KF_Literata-Regular.ttf', 'KF_Literata-Italic.ttf', 'KF_Literata-Bold.ttf', 'KF_Literata-BoldItalic.ttf'],
    },
    {
        id: 'membo',
        name: 'Membo',
        collection: 'extra',
        files: ['KF_Membo-Regular.ttf', 'KF_Membo-Italic.ttf', 'KF_Membo-Bold.ttf', 'KF_Membo-BoldItalic.ttf'],
    },
    {
        id: 'newsreader',
        name: 'Newsreader',
        collection: 'extra',
        files: ['KF_Newsreader-Regular.ttf', 'KF_Newsreader-Italic.ttf', 'KF_Newsreader-Bold.ttf', 'KF_Newsreader-BoldItalic.ttf'],
    },
    {
        id: 'ninepoint',
        name: 'NinePoint',
        collection: 'extra',
        files: ['KF_NinePoint-Regular.ttf', 'KF_NinePoint-Italic.ttf', 'KF_NinePoint-Bold.ttf', 'KF_NinePoint-BoldItalic.ttf'],
    },
    {
        id: 'publica',
        name: 'Publica',
        collection: 'extra',
        files: ['KF_Publica-Regular.ttf', 'KF_Publica-Italic.ttf', 'KF_Publica-Bold.ttf', 'KF_Publica-BoldItalic.ttf'],
    },
    {
        id: 'publica-wide',
        name: 'Publica Wide',
        collection: 'extra',
        files: ['KF_Publica_Wide-Regular.ttf', 'KF_Publica_Wide-Italic.ttf'],
    },
    {
        id: 'readerly',
        name: 'Readerly',
        collection: 'extra',
        files: ['KF_Readerly-Regular.ttf', 'KF_Readerly-Italic.ttf', 'KF_Readerly-Bold.ttf', 'KF_Readerly-BoldItalic.ttf'],
    },
    {
        id: 'sable',
        name: 'Sable',
        collection: 'extra',
        files: ['KF_Sable-Regular.ttf', 'KF_Sable-Italic.ttf', 'KF_Sable-Bold.ttf', 'KF_Sable-BoldItalic.ttf'],
    },
    {
        id: 'scarlet',
        name: 'Scarlet',
        collection: 'extra',
        files: ['KF_Scarlet-Regular.ttf', 'KF_Scarlet-Italic.ttf', 'KF_Scarlet-Bold.ttf', 'KF_Scarlet-BoldItalic.ttf'],
    },
    {
        id: 'tabula',
        name: 'Tabula',
        collection: 'extra',
        files: ['KF_Tabula-Regular.ttf', 'KF_Tabula-Italic.ttf', 'KF_Tabula-Bold.ttf', 'KF_Tabula-BoldItalic.ttf'],
    },
    {
        id: 'technical',
        name: 'Technical',
        collection: 'extra',
        files: ['KF_Technical-Regular.ttf', 'KF_Technical-Italic.ttf', 'KF_Technical-Bold.ttf', 'KF_Technical-BoldItalic.ttf'],
    },
    {
        id: 'yrsa',
        name: 'Yrsa',
        collection: 'extra',
        files: ['KF_Yrsa-Regular.ttf', 'KF_Yrsa-Italic.ttf', 'KF_Yrsa-Bold.ttf', 'KF_Yrsa-BoldItalic.ttf'],
    },
    {
        id: 'zilla-slab',
        name: 'Zilla Slab',
        collection: 'extra',
        files: ['KF_Zilla_Slab-Regular.ttf', 'KF_Zilla_Slab-Italic.ttf', 'KF_Zilla_Slab-Bold.ttf', 'KF_Zilla_Slab-BoldItalic.ttf'],
    },
];
