/**
 * Plain-text manual-installation instructions.
 *
 * The wizard's final screen shows step-by-step instructions for the manual
 * (download a ZIP) approach. When that ZIP is built we also bundle an
 * `instructions.txt` so the same guidance travels with the download. This
 * module is the single source of truth for that text: the NickelMenu and
 * custom-patch download flows call into it, and the copy is kept identical to
 * what the on-screen steps describe.
 *
 * The functions are pure (take a context, return a string) so they can be unit
 * tested directly. `date` defaults to "now" but is injectable for tests.
 */

// Where to learn how to recover a hard-locked / bricked device. Mirrors the
// "manually reset your Kobo" link in the on-screen Disclaimer.
export const KOBO_RESET_HELP_URL = 'https://help.kobo.com/hc/en-us/articles/360017605314';

// Description shown under the ExcludeSyncFolders config step. Kept here so the
// on-screen step (nickelmenu-flow.js) and the instructions.txt stay identical.
export const CONF_DESC_EXCLUDE_CALIBRE =
    'This prevents new books in the calibre folder from showing up in Kobo\'s list of books. ' +
    'Move Calibre-transferred books into a "calibre" folder first.';
export const CONF_DESC_DEFAULT =
    'This prevents the Kobo from incorrectly identifying certain files as books in your library.';

/** Format a Date as a readable UTC timestamp, e.g. `2026-06-14 13:45 UTC`. */
function formatTimestamp(date) {
    const pad = (n) => String(n).padStart(2, '0');
    return `${date.getUTCFullYear()}-${pad(date.getUTCMonth() + 1)}-${pad(date.getUTCDate())} ` +
        `${pad(date.getUTCHours())}:${pad(date.getUTCMinutes())} UTC`;
}

/** Underline a heading with `-` to its own length. */
function heading(text) {
    return `${text}\n${'-'.repeat(text.length)}`;
}

/**
 * Render a list of steps (each an array of already-wrapped lines) as a numbered
 * list with continuation lines indented to line up under the first line's text.
 */
function renderSteps(steps) {
    return steps.map((lines, index) => {
        const marker = `${index + 1}. `;
        const indent = ' '.repeat(marker.length);
        const [first, ...rest] = lines;
        return [marker + first, ...rest.map((line) => (line ? indent + line : ''))].join('\n');
    }).join('\n\n');
}

/** Shared file header: what generated this, which version, and when. */
function header(version, date) {
    return [
        'KoboPatch Web UI — Manual installation instructions',
        '===================================================',
        '',
        `Generated by KoboPatch Web UI (version ${version}) on ${formatTimestamp(date)}.`,
        'https://github.com/nicoverbruggen/kobopatch-webui',
    ].join('\n');
}

/** Shared "before you start" safety disclaimer, mirroring the on-screen one. */
function disclaimer() {
    return [
        heading('Before you start'),
        '',
        'Both methods modify system files. While as many possible precautions are',
        'taken to avoid anything going wrong, you should still know how to manually',
        'reset your Kobo if needed, as there are always risks involved with these',
        'types of modifications. You apply them at your own risk.',
        '',
        'If your device becomes unresponsive or hard-locked, follow Kobo\'s guide on',
        'how to manually reset your Kobo:',
        KOBO_RESET_HELP_URL,
    ].join('\n');
}

/** Word-wrap a paragraph to a max line width, returning an array of lines. */
function wrapText(text, width = 70) {
    const lines = [];
    let line = '';
    for (const word of text.split(/\s+/).filter(Boolean)) {
        if (line && line.length + 1 + word.length > width) {
            lines.push(line);
            line = word;
        } else {
            line = line ? `${line} ${word}` : word;
        }
    }
    if (line) lines.push(line);
    return lines;
}

/**
 * Render the `Kobo eReader.conf` edits as a single copy-paste block: literal
 * `[Section]` headers, each followed by its `key=value` lines, with a blank line
 * between sections. The ExcludeSyncFolders line (when present) leads as a
 * `[FeatureSettings]` entry so every conf edit reads the same way.
 */
function renderConfBlock(confLine, confSettings) {
    const sections = new Map();
    const add = (section, line) => {
        if (!sections.has(section)) sections.set(section, []);
        sections.get(section).push(line);
    };

    if (confLine) add('FeatureSettings', confLine);
    for (const { section, key, value } of confSettings) add(section, `${key}=${value}`);

    const lines = [];
    for (const [section, settingLines] of sections) {
        if (lines.length > 0) lines.push('');
        lines.push(`[${section}]`, ...settingLines);
    }
    return lines;
}

/**
 * Build the instructions.txt body for the NickelMenu manual download.
 *
 * @param {object}  ctx
 * @param {string}  ctx.version          App version string.
 * @param {Date}    [ctx.date]           Generation timestamp.
 * @param {boolean} ctx.isPreset         Whether the curated preset was chosen
 *                                       (only then is the conf step relevant).
 * @param {string}  [ctx.confLine]       The ExcludeSyncFolders line to add.
 * @param {object[]}[ctx.confSettings]   Feature `Kobo eReader.conf` settings.
 * @param {boolean} [ctx.hasExcludeCalibre]
 */
export function buildNickelMenuInstructions({
    version,
    date = new Date(),
    isPreset,
    confLine = '',
    confSettings = [],
    hasExcludeCalibre = false,
} = {}) {
    const steps = [];

    steps.push(['Connect your Kobo via USB so it appears as a removable drive.']);

    if (isPreset) {
        const confBlock = renderConfBlock(confLine, confSettings);
        const confNote = hasExcludeCalibre ? CONF_DESC_EXCLUDE_CALIBRE : CONF_DESC_DEFAULT;
        steps.push([
            'Open .kobo/Kobo/Kobo eReader.conf in a text editor and add the',
            'settings shown below. Keep each line under its [Section] header,',
            'adding a section if it is missing and replacing any existing line',
            'that has the same key. Do not replace the entire file.',
            '',
            ...confBlock.map((line) => (line ? `    ${line}` : '')),
            '',
            ...wrapText(confNote),
        ]);

        steps.push([
            'Safely eject the Kobo, then power it off by holding the power',
            'button until it says "Powered off". Press the power button again',
            'to boot it back up. The config change takes effect after reboot.',
            'Reconnect the Kobo via USB afterwards.',
        ]);
    }

    steps.push([
        'Extract the downloaded ZIP to the root of the Kobo drive, preserving',
        'the folder structure. Make sure hidden folders like .kobo and .adds',
        'are also copied.',
    ]);

    steps.push([
        'Safely eject the Kobo before unplugging the USB cable — it will',
        'reboot and install NickelMenu automatically.',
    ]);

    return [
        header(version, date),
        '',
        disclaimer(),
        '',
        heading('Installation steps'),
        '',
        renderSteps(steps),
        '',
    ].join('\n');
}

/**
 * Build the instructions.txt body for the custom-patch manual download.
 *
 * @param {object} ctx
 * @param {string} ctx.version      App version string.
 * @param {Date}   [ctx.date]       Generation timestamp.
 * @param {string} [ctx.deviceName] Friendly device name (e.g. "Kobo Libra Color").
 */
export function buildPatchesInstructions({ version, date = new Date(), deviceName = 'Kobo' } = {}) {
    const steps = [
        [`Connect your ${deviceName} via USB so it appears as a removable drive.`],
        [
            'Extract the downloaded ZIP to the root of the Kobo drive, preserving',
            'the folder structure. Make sure the hidden .kobo folder is also',
            'copied.',
        ],
        [
            'Safely eject the Kobo before unplugging the USB cable — it will',
            'reboot and apply the patches automatically.',
        ],
    ];

    return [
        header(version, date),
        '',
        disclaimer(),
        '',
        heading('Installation steps'),
        '',
        renderSteps(steps),
        '',
    ].join('\n');
}
