export const TL = {
    NAV_NICKELMENU: ['Device', 'Mode', 'Configure', 'Backup', 'Review', 'Install'],
    NAV_NICKELMENU_REMOVE: ['Device', 'Mode', 'Configure', 'Backup', 'Review', 'Remove'],
    NAV_NICKELMENU_MANUAL_REMOVE: ['Device', 'Mode', 'Configure', 'Remove'],
    NAV_PATCHES: ['Device', 'Mode', 'Patches', 'Build', 'Install'],
    NAV_DEFAULT: ['Device', 'Mode', 'Patches', 'Build', 'Install'],

    BUTTON: {
        RESTORE_ORIGINAL: 'Restore Original Software',
        BUILD_PATCHED: 'Build Patched Software',
        WRITE_TO_KOBO: 'Write to Kobo',
        REMOVE_FROM_KOBO: 'Remove from Kobo',
        WRITING: 'Writing...',
        WRITTEN: 'Written',
        GO_BACK: '\u2039 Back',
        SELECT_DIFFERENT_PATCHES: '\u2039 Select different patches',
    },

    STATUS: {
        DEVICE_RECOGNIZED: 'Your device has been recognized. You can continue to the next step!',
        NM_REMOVED_ON_REBOOT: 'NickelMenu will be removed on next reboot.',
        NM_INSTALLED: 'NickelMenu has been installed on your Kobo. To complete the installation, follow the instructions below.',
        NM_DOWNLOAD_READY: 'Your NickelMenu package is ready to download. After downloading, a list of installation steps will be displayed.',
        NM_WILL_BE_REMOVED: 'NickelMenu will be updated and marked for removal. It will uninstall itself when your Kobo reboots after you safely eject your device:',
        NM_SELECTED_REMOVALS: 'Selected removals:',
        NM_KEPT_FEATURES: 'These items and their files will be kept:',
        NM_WILL_BE_INSTALLED: 'The following will be installed on your Kobo:',
        NM_NICKEL_ROOT_TGZ: 'NickelMenu (KoboRoot.tgz)',
        NM_REMOVAL_NICKELMENU: 'NickelMenu',
        NM_REMOVAL_HINT: 'Removes NickelMenu from your device. Your device will restart automatically.',
        NM_REMOVAL_MANUAL_HINT: 'Shows instructions for manually removing NickelMenu from a Kobo.',
        NM_REMOVAL_DISABLED: 'Removes NickelMenu from your device. Only available when a Kobo with NickelMenu installed is connected.',
        NM_PRESET_CONFLICT: 'This Kobo seems to have been modded before.',
        PATCH_COUNT_ZERO: 'No patches selected \u2014 continuing will restore the original unpatched software.',
        PATCH_COUNT_ONE: '1 patch selected.',
        PATCH_COUNT_MULTI: (n) => `${n} patches selected.`,
        FIRMWARE_WILL_BE_DOWNLOADED: 'will be downloaded automatically from Kobo\u2019s servers and will be patched after the download completes.',
        RESTORE_ORIGINAL: 'will be downloaded and extracted without modifications to restore the original unpatched software.',
        BUILDING_STARTING: 'Starting...',
        DOWNLOADING: 'Downloading software update...',
        DOWNLOADING_PROGRESS: (received, total, pct) => `Downloading software update... ${received} / ${total} (${pct}%)`,
        EXTRACTING: 'Extracting KoboRoot.tgz...',
        APPLYING_PATCHES: 'Applying patches...',
        NO_FIRMWARE_URL: 'No download URL available for this device.',
        WRITE_FAILED: (msg) => `Failed to write KoboRoot.tgz: ${msg}`,
        NM_INSTALL_FAILED: (msg) => `NickelMenu installation failed: ${msg}`,
        EXTRACT_FAILED: 'KoboRoot.tgz not found in software update',
    },

    ERROR: {
        PATCH_FAILED: 'The patch failed to apply',
        SOMETHING_WENT_WRONG: 'Something went wrong',
        LOAD_PATCHES_FAILED: (v) => `Could not load patches for software version ${v}`,
    },

    PATCH: {
        NONE: 'None (do not patch)',
        MODIFIED: 'modified',
        MODIFIED_TITLE: 'You edited this patch’s definition.',
        DISCARD_EDITS_CONFIRM: 'You have unsaved edits to one or more patches. Going back will discard them. Continue?',
        RELOAD_OFFER: 'You connected a device that is or was previously patched. If you need to re-apply the previous patches, you can restore them, including any manual edits.',
        RELOAD_APPLIED: 'Previously applied patches have been reloaded, including any manual edits.',
        RELOAD_NONE_MATCHED: 'None of the previously applied patches could be matched to the patches for this software version.',
    },

};
