import { writeAuditLog } from '../kobo/audit-log.js';
import { NM_ITEMS_FILE, nickelMenuManifestPath } from './constants.js';
import JSZip from 'jszip';
import { buildTarGz, parseTarGz } from './archive.js';
import { fetchOrThrow, fetchWithProgress, downloadProgress } from '../shell/dom.js';
import { installableAssetUrl, installableSize } from './installables.js';
import { buildNickelMenuInstructions } from '../shell/instructions.js';
import { removeExcludeSyncFoldersLine, revertableConfSettings, setConfSetting, setExcludeSyncFoldersLine } from '../kobo/configuration.js';

import { menuItemPosition } from './features/menu-order.js';
import excludeCalibre from './features/exclude-calibre/index.js';
import { buildExcludeSyncFoldersLine, legacyBrokenExcludeSyncFoldersLines } from '../kobo/sync-exclusions.js';

export function getExcludeSyncFoldersLine(features = []) {
    return buildExcludeSyncFoldersLine({
        excludeCalibre: features.some((f) => f.id === excludeCalibre.id),
    });
}

/**
 * Memoized asset fetch shared across one install run. Several features can ship
 * the same shared asset (e.g. every home-content hider ships the identical
 * toggle script); without this they would each fetch it independently before the
 * installer de-duplicates the writes by path. Keyed by URL, it caches the
 * in-flight promise so concurrent and repeated requests collapse to one fetch.
 * Failures are not cached, so a transient error can be retried on a later run.
 */
function loadAssetCached(assetCache, url) {
    let pending = assetCache.get(url);
    if (!pending) {
        pending = fetchOrThrow(url, `Failed to load asset ${url}`)
            .then((resp) => resp.arrayBuffer())
            .then((buf) => new Uint8Array(buf))
            .catch((err) => {
                assetCache.delete(url);
                throw err;
            });
        assetCache.set(url, pending);
    }
    return pending;
}

/**
 * Create the context passed to a feature's installer-time hooks (`install` and
 * `postProcess`). Every hook receives `deviceInfo` and the selected `features`
 * so features can adapt to the connected hardware and to what else is being
 * installed; installer-time hooks additionally get `bundledAsset` and
 * `progress`. `bundledAsset(url)` fetches a Vite-tracked asset URL through one
 * per-run cache (`assetCache`), so an asset used by several features is fetched
 * only once.
 */
function createContext(
    progressFn,
    deviceInfo = null,
    features = [],
    { menuCustomization = null, tabsCustomization = null, fontsCustomization = null, assetCache = new Map() } = {},
) {
    return {
        bundledAsset(url) {
            return loadAssetCached(assetCache, url);
        },
        progress(msg, detail, fraction) {
            progressFn(msg, detail, fraction);
        },
        deviceInfo,
        features,
        menuCustomization,
        tabsCustomization,
        fontsCustomization,
    };
}

/**
 * Assemble the NickelMenu config file from the selected features' `menuItems`
 * hooks. Each feature contributes entries (`{ id, lines }`); they are ordered by
 * their id's position in MENU_ITEM_ORDER (see features/menu-order.js) and
 * rendered (entries separated by a blank line, trailing newline). The output is
 * prefixed with a comment identifying it as generated by this tool. Returns null
 * when no feature contributes any entries.
 */
function buildItemsFile(features, deviceInfo, menuCustomization = null) {
    const menuCtx = { deviceInfo, features, menuCustomization };
    const entries = [];
    const seenIds = new Set();
    for (const feature of features) {
        if (!feature.menuItems) continue;
        for (const entry of feature.menuItems(menuCtx)) {
            // Several features can contribute the same shared entry — e.g. every
            // home-content hider offers the one "Minimal Home" toggle.
            // Keep the first; the duplicates are identical.
            if (seenIds.has(entry.id)) continue;
            seenIds.add(entry.id);
            entries.push(entry);
        }
    }
    if (entries.length === 0) return null;

    entries.sort((a, b) => menuItemPosition(a.id) - menuItemPosition(b.id));
    const content = entries.map((entry) => entry.lines.join('\n')).join('\n\n') + '\n';
    return '# Generated by KoboPatch Web UI (https://kp.nicoverbruggen.be)\n' + content;
}

export class NickelMenuInstaller {
    constructor() {
        this.nickelMenuTgz = null;
    }

    /**
     * Download and cache NickelMenu's KoboRoot.tgz. Upstream NickelMenu ships a
     * bare KoboRoot.tgz (stored locally as NickelMenu.tgz to avoid confusion with
     * the generated .kobo/KoboRoot.tgz), so the bytes are used verbatim.
     */
    async loadNickelMenu(progressFn) {
        if (this.nickelMenuTgz) return;
        const label = 'Downloading NickelMenu...';
        progressFn(label);
        this.nickelMenuTgz = await fetchWithProgress(
            installableAssetUrl('nickelmenu', 'NickelMenu.tgz'),
            downloadProgress(progressFn, label, await installableSize('nickelmenu')),
            'Failed to download NickelMenu',
        );
    }

    /**
     * Get the base NickelMenu KoboRoot.tgz.
     */
    async getKoboRootTgz() {
        if (!this.nickelMenuTgz) throw new Error('NickelMenu KoboRoot.tgz not loaded');
        return this.nickelMenuTgz;
    }

    /**
     * Build the effective KoboRoot.tgz written to the device.
     *
     * The device only processes one `.kobo/KoboRoot.tgz` per boot, so any feature
     * that ships its own KoboRoot.tgz payload (e.g. NickelClock, whose plugin
     * cannot be expressed as ordinary onboard files) must be merged into a single
     * archive alongside NickelMenu's. A feature declares this generically via a
     * `koboRootEntries(ctx)` hook returning tar entries (`{ path, data, mode }`).
     *
     * When no selected feature contributes entries — the common case — the base
     * NickelMenu tgz is returned verbatim (no parse/rebuild), so the default
     * install path is byte-for-byte unchanged. Only when a feature contributes do
     * we parse the base archive and rebuild a merged one.
     */
    async buildKoboRootTgz(features = [], progressFn = () => {}, deviceInfo = null) {
        const baseTgz = await this.getKoboRootTgz();

        const extraEntries = [];
        for (const feature of features) {
            if (!feature.koboRootEntries) continue;
            const ctx = createContext(progressFn, deviceInfo, features);
            extraEntries.push(...(await feature.koboRootEntries(ctx)));
        }
        if (extraEntries.length === 0) return baseTgz;

        // Merge base + feature entries, keeping the first occurrence of any path.
        const merged = [];
        const seenPaths = new Set();
        for (const entry of [...(await parseTarGz(baseTgz)), ...extraEntries]) {
            if (seenPaths.has(entry.path)) continue;
            seenPaths.add(entry.path);
            merged.push(entry);
        }
        return buildTarGz(merged);
    }

    /**
     * Run selected features and collect all files to write.
     * @param {object[]} features - feature modules to run
     * @param {function} progressFn
     * @returns {{ path: string, data: Uint8Array|string }[]}
     */
    async collectFiles(features, progressFn, deviceInfo = null, { menuCustomization = null, tabsCustomization = null, fontsCustomization = null } = {}) {
        let files = [];
        const featureFiles = {};

        // One asset cache for the whole run, so an asset several features share
        // (e.g. the home-content hiders' toggle script) is fetched only once.
        const assetCache = new Map();

        // Run install() for features that have it
        for (const feature of features) {
            if (!feature.install) continue;
            const ctx = createContext(progressFn, deviceInfo, features, { menuCustomization, tabsCustomization, fontsCustomization, assetCache });
            progressFn(`Setting up: ${feature.title}...`);
            const result = await feature.install(ctx);
            files.push(...result);
            featureFiles[feature.id] = result.map((f) => f.path);
        }

        // De-duplicate shared install files by path — e.g. several home-content
        // hiders each ship the identical toggle script. Keep the first write.
        const seenPaths = new Set();
        files = files.filter((file) => {
            if (seenPaths.has(file.path)) return false;
            seenPaths.add(file.path);
            return true;
        });

        // Assemble the NickelMenu items file from the features' menuItems hooks.
        const itemsContent = buildItemsFile(features, deviceInfo, menuCustomization);
        if (itemsContent !== null) {
            files.push({ path: NM_ITEMS_FILE, data: itemsContent });
        }

        // Run postProcess() for features that have it.
        const itemsFile = files.find((f) => f.path === NM_ITEMS_FILE);
        for (const feature of features) {
            if (!feature.postProcess) continue;
            const ctx = createContext(progressFn, deviceInfo, features, { menuCustomization, tabsCustomization, fontsCustomization, assetCache });
            files = feature.postProcess(files, ctx);
        }

        // Encode the items file to bytes for writing.
        if (itemsFile && typeof itemsFile.data === 'string') {
            itemsFile.data = new TextEncoder().encode(itemsFile.data);
        }

        return { files, featureFiles };
    }

    /**
     * Install to a connected Kobo device via File System Access API.
     */
    async installToDevice(device, features, progressFn, { audit = null, menuCustomization = null, tabsCustomization = null, fontsCustomization = null } = {}) {
        await this.loadNickelMenu(progressFn);

        const tgz = await this.buildKoboRootTgz(features, progressFn, device.deviceInfo);

        let collectedFiles = [];
        let featureFiles = {};

        if (features.length > 0) {
            progressFn('Preparing Kobo eReader.conf...');
            const eReaderConfData = await this.buildEReaderConfData(device, features, fontsCustomization);

            const result = await this.collectFiles(features, progressFn, device.deviceInfo, { menuCustomization, tabsCustomization, fontsCustomization });
            collectedFiles = result.files;
            featureFiles = result.featureFiles;

            progressFn('Updating Kobo eReader.conf...');
            await device.writeFile(['.kobo', 'Kobo', 'Kobo eReader.conf'], eReaderConfData);
            this.recordEReaderConfUpdates(features, device.deviceInfo, audit, fontsCustomization);

            // Thousands of files over USB for a KOReader install: the slowest
            // part of the whole thing, and the one non-download step that knows
            // exactly where it is. Each file is counted *after* its write
            // resolves, the way a download counts bytes actually received —
            // reporting the write we are about to attempt would leave the bar a
            // file ahead of the device, sitting at 100% while the last one goes.
            const total = collectedFiles.length;
            for (let i = 0; i < total; i++) {
                const { path, data } = collectedFiles[i];
                const fileData = typeof data === 'string' ? new TextEncoder().encode(data) : data;
                await device.writeFile(path.split('/'), fileData);
                audit?.record(`Wrote ${path} (${fileData.length} bytes)`);
                progressFn('Writing files to your Kobo...', `${i + 1} of ${total} files`, (i + 1) / total);
            }
        }

        // Write the install manifest
        const manifest = this.buildManifest(features, collectedFiles, featureFiles, device.deviceInfo, audit);
        if (manifest) {
            await this.writeManifest(device, manifest);
        }

        progressFn('Writing KoboRoot.tgz...');
        await device.writeFile(['.kobo', 'KoboRoot.tgz'], tgz);
        audit?.record(`Installed NickelMenu: wrote .kobo/KoboRoot.tgz (${tgz.length} bytes)`);

        await writeAuditLog(audit, device);
        progressFn('Done.');
    }

    /**
     * Build a zip for manual download.
     */
    async buildDownloadZip(
        features,
        progressFn,
        deviceInfo = null,
        { menuCustomization = null, tabsCustomization = null, fontsCustomization = null, isPreset = features.length > 0 } = {},
    ) {
        await this.loadNickelMenu(progressFn);

        progressFn('Building download package...');
        const zip = new JSZip();

        const tgz = await this.buildKoboRootTgz(features, progressFn, deviceInfo);
        zip.file('.kobo/KoboRoot.tgz', tgz);

        let collectedFiles = [];
        let featureFiles = {};

        if (features.length > 0) {
            const result = await this.collectFiles(features, progressFn, deviceInfo, { menuCustomization, tabsCustomization, fontsCustomization });
            collectedFiles = result.files;
            featureFiles = result.featureFiles;
            for (const { path, data } of collectedFiles) {
                const fileData = typeof data === 'string' ? new TextEncoder().encode(data) : data;
                zip.file(path, fileData);
            }
        }

        // Include the install manifest so the downloaded archive carries the same
        // definitional info about the chosen features that a USB install writes.
        const manifest = this.buildManifest(features, collectedFiles, featureFiles, deviceInfo, null);
        if (manifest) {
            const data = new TextEncoder().encode(JSON.stringify(manifest, null, 2) + '\n');
            zip.file(nickelMenuManifestPath.join('/'), data);
        }

        // Bundle the same manual-install guidance the wizard shows on screen,
        // so the steps travel with the download.
        zip.file('instructions.txt', this.buildInstructionsText(features, deviceInfo, isPreset, fontsCustomization));

        progressFn('Compressing...');
        let shown = -1;
        const result = await zip.generateAsync({ type: 'uint8array' }, ({ percent }) => {
            const rounded = Math.round(percent);
            if (rounded === shown) return;
            shown = rounded;
            progressFn('Compressing...', `${rounded}%`, rounded / 100);
        });
        progressFn('Done.');
        return result;
    }

    /**
     * Render the plain-text manual-install instructions bundled in the download
     * ZIP. The conf steps are only relevant for a curated preset install, which
     * is exactly when the on-screen instructions show them too.
     */
    buildInstructionsText(features, deviceInfo, isPreset, fontsCustomization = null) {
        const version = (typeof globalThis.__APP_VERSION__ !== 'undefined' ? globalThis.__APP_VERSION__ : null) || 'unknown';
        const settingsCtx = { deviceInfo: deviceInfo ?? null, features, fontsCustomization };
        const confSettings = isPreset ? features.flatMap((feature) => (feature.confSettings ? feature.confSettings(settingsCtx) : [])) : [];
        return buildNickelMenuInstructions({
            version,
            isPreset,
            confLine: getExcludeSyncFoldersLine(features),
            confSettings,
            hasExcludeCalibre: features.some((f) => f.id === excludeCalibre.id),
        });
    }

    /**
     * Add or update ExcludeSyncFolders in Kobo eReader.conf.
     * @param {object[]} features - selected features; if 'exclude-calibre' is included, the calibre folder is excluded.
     */
    async updateEReaderConf(device, features = [], audit = null) {
        const confPath = ['.kobo', 'Kobo', 'Kobo eReader.conf'];
        const data = await this.buildEReaderConfData(device, features);
        await device.writeFile(confPath, data);
        this.recordEReaderConfUpdates(features, device.deviceInfo, audit);
    }

    async buildEReaderConfData(device, features = [], fontsCustomization = null) {
        return new TextEncoder().encode(await this.buildEReaderConfContent(device, features, fontsCustomization));
    }

    async buildEReaderConfContent(device, features = [], fontsCustomization = null) {
        const confPath = ['.kobo', 'Kobo', 'Kobo eReader.conf'];
        const settingLine = getExcludeSyncFoldersLine(features);
        let content = setExcludeSyncFoldersLine((await device.readFile(confPath)) || '', settingLine);

        // Apply any Kobo eReader.conf settings declared by selected features
        // (e.g. better-typography's reading/rendering preferences). Features get
        // the full selection so they can adapt (e.g. only set a default font when
        // that font is part of the fonts selection being installed).
        const settingsCtx = { deviceInfo: device.deviceInfo, features, fontsCustomization };
        for (const feature of features) {
            if (!feature.confSettings) continue;
            for (const { section, key, value } of feature.confSettings(settingsCtx)) {
                content = setConfSetting(content, section, key, value);
            }
        }

        return content;
    }

    recordEReaderConfUpdates(features = [], deviceInfo = null, audit = null, fontsCustomization = null) {
        if (!audit) return;
        const settingLine = getExcludeSyncFoldersLine(features);
        audit.record(`Set Kobo eReader.conf ExcludeSyncFolders=${settingLine}`);

        const settingsCtx = { deviceInfo, features, fontsCustomization };
        for (const feature of features) {
            if (!feature.confSettings) continue;
            for (const { section, key, value } of feature.confSettings(settingsCtx)) {
                audit.record(`Set Kobo eReader.conf [${section}] ${key}=${value}`);
            }
        }
    }

    /**
     * Remove ExcludeSyncFolders from Kobo eReader.conf.
     */
    async removeExcludeSyncFolders(device) {
        const confPath = ['.kobo', 'Kobo', 'Kobo eReader.conf'];
        const content = await device.readFile(confPath);
        if (!content || !content.includes('ExcludeSyncFolders')) return;

        const updated = removeExcludeSyncFoldersLine(content);
        if (updated !== content) {
            await device.writeFile(confPath, new TextEncoder().encode(updated));
        }
    }

    /**
     * Replace legacy malformed ExcludeSyncFolders values with the default
     * generated line when uninstall keeps sync exclusions in place.
     */
    async repairLegacyExcludeSyncFolders(device) {
        const confPath = ['.kobo', 'Kobo', 'Kobo eReader.conf'];
        const content = await device.readFile(confPath);
        if (!content || !content.includes('ExcludeSyncFolders')) return;

        let updated = content;
        for (const line of Object.values(legacyBrokenExcludeSyncFoldersLines)) {
            if (!updated.includes(line)) continue;
            updated = setExcludeSyncFoldersLine(updated, buildExcludeSyncFoldersLine());
        }

        if (updated !== content) {
            await device.writeFile(confPath, new TextEncoder().encode(updated));
        }
    }

    buildManifest(features, collectedFiles, featureFiles, deviceInfo, audit) {
        const selected = features.map((f) => f.id);
        const settingsCtx = { deviceInfo, features };
        const manifestFeatures = {};

        for (const feature of features) {
            const entry = {};

            if (feature.directories) {
                entry.directories = feature.directories;
            } else {
                entry.files = [];
                const paths = featureFiles[feature.id] || [];
                for (const path of paths) {
                    entry.files.push({ path, type: 'file' });
                }
            }

            const conf = revertableConfSettings(feature, settingsCtx).map((s) => ({
                section: s.section,
                key: s.key,
                value: s.value,
                revertTo: s.revertTo ?? null,
            }));
            if (conf.length > 0) entry.conf = conf;

            manifestFeatures[feature.id] = entry;
        }

        const version = (typeof globalThis.__APP_VERSION__ !== 'undefined' ? globalThis.__APP_VERSION__ : null) || 'unknown';
        const timestamp = audit ? audit.startedAt.toISOString() : new Date().toISOString();
        const firmware = deviceInfo?.firmware || null;
        const channel = deviceInfo?.channel || null;

        return {
            selected,
            features: manifestFeatures,
            meta: {
                writer: { name: 'kobopatch-webui', version },
                installed: { timestamp, firmware, channel },
            },
        };
    }

    async writeManifest(device, manifest) {
        const data = new TextEncoder().encode(JSON.stringify(manifest, null, 2) + '\n');
        await device.writeFile(nickelMenuManifestPath, data);
    }
}
