import { AUDIT_LOG_DIRECTORY } from '../kobo/audit-log.js';
import { NM_ITEMS_FILE } from './constants.js';
import JSZip from 'jszip';
import { fetchOrThrow } from '../shell/dom.js';
import {
    removeExcludeSyncFoldersLine,
    setConfSetting,
    setExcludeSyncFoldersLine,
} from '../kobo/configuration.js';

import customMenu from './features/custom-menu/index.js';
import additionalFonts from './features/additional-fonts/index.js';
import betterTypography from './features/better-typography/index.js';
import cadmus from './features/cadmus/index.js';
import koreader from './features/koreader/index.js';
import simplifyTabs from './features/simplify-tabs/index.js';
import { homeHiders } from './features/hide-home-content/index.js';
import { menuItemPosition } from './features/menu-order.js';
import screensaver from './features/screensaver/index.js';
import excludeCalibre from './features/exclude-calibre/index.js';
import sideloadedMode from './features/sideloaded-mode/index.js';
import {
    buildExcludeSyncFoldersLine,
    legacyBrokenExcludeSyncFoldersLines,
} from '../kobo/sync-exclusions.js';

export function getExcludeSyncFoldersLine(features = []) {
    return buildExcludeSyncFoldersLine({
        excludeCalibre: features.some(f => f.id === excludeCalibre.id),
    });
}

/**
 * The Kobo eReader.conf settings a feature both applies AND owns for removal:
 * the entries its `confSettings` declares with `revertable: true`. The installer
 * applies every `confSettings` entry; this subset is also what the flow detects
 * the feature by and what the uninstaller reverts (to `revertTo`, or removes the
 * line when `revertTo` is null/absent). Declaring `revertable`/`revertTo` on the
 * setting itself keeps each reverted key defined once, in `confSettings`, instead
 * of being repeated in `cleanup.detectConf`/`cleanup.revertConf`. A setting left
 * without `revertable` is applied but never clawed back (e.g. a general reading
 * preference).
 */
export function revertableConfSettings(feature, ctx = {}) {
    if (!feature.confSettings) return [];
    return feature.confSettings(ctx).filter(setting => setting.revertable);
}

/**
 * All available NickelMenu features in display order.
 * Features with `required: true` are always included in the preset.
 * Features with `postProcess` modify files produced by other features.
 */
export const NICKELMENU_FEATURES = [
    customMenu,
    simplifyTabs,       // postProcess must run before sideloadedMode (home-tab override)
    ...homeHiders,
    additionalFonts,
    betterTypography,
    koreader,
    cadmus,
    // "Advanced" section — less common power-user options, rendered last and
    // collapsed by default in the feature selection step.
    sideloadedMode,     // postProcess comments out the home-tab override added by simplifyTabs
    screensaver,
    excludeCalibre,
];

/**
 * Create the context passed to a feature's installer-time hooks (`install` and
 * `postProcess`). Every hook receives `deviceInfo` and the selected `features`
 * so features can adapt to the connected hardware and to what else is being
 * installed; installer-time hooks additionally get `asset` and `progress`.
 * Assets are fetched at runtime from the feature's directory under
 * /js/nickelmenu/features/<id>/.
 */
function createContext(feature, progressFn, deviceInfo = null, features = [], menuCustomization = null) {
    const basePath = `js/nickelmenu/features/${feature.id}/`;
    return {
        async asset(relativePath) {
            const url = basePath + relativePath;
            const resp = await fetchOrThrow(url, `Failed to load asset ${url}`);
            return new Uint8Array(await resp.arrayBuffer());
        },
        progress(msg) {
            progressFn(msg);
        },
        deviceInfo,
        features,
        menuCustomization,
    };
}

/**
 * Assemble the NickelMenu config file from the selected features' `menuItems`
 * hooks. Each feature contributes entries (`{ id, lines }`); they are ordered by
 * their id's position in MENU_ITEM_ORDER (see features/menu-order.js) and
 * rendered (entries separated by a blank line, trailing newline). The output is
 * prefixed with a comment identifying it as generated by this tool. Returns null
 * when no feature contributes any entries.
 */
function buildItemsFile(features, deviceInfo, menuCustomization = null) {
    const menuCtx = { deviceInfo, features, menuCustomization };
    const entries = [];
    const seenIds = new Set();
    for (const feature of features) {
        if (!feature.menuItems) continue;
        for (const entry of feature.menuItems(menuCtx)) {
            // Several features can contribute the same shared entry — e.g. every
            // home-content hider offers the one "Minimal Home" toggle.
            // Keep the first; the duplicates are identical.
            if (seenIds.has(entry.id)) continue;
            seenIds.add(entry.id);
            entries.push(entry);
        }
    }
    if (entries.length === 0) return null;

    entries.sort((a, b) => menuItemPosition(a.id) - menuItemPosition(b.id));
    const content = entries.map(entry => entry.lines.join('\n')).join('\n\n') + '\n';
    return '# Generated by KoboPatch Web UI (https://kp.nicoverbruggen.be)\n' + content;
}

/**
 * Best-effort write of the on-device audit log. Logging must never fail an
 * install or removal, so write errors are logged and swallowed.
 */
export async function writeAuditLog(audit, device, logger = console) {
    if (!audit) return;
    try {
        await audit.write(device);
    } catch (err) {
        logger.warn('Could not write audit log:', err);
    }
}

export class NickelMenuInstaller {
    constructor() {
        this.nickelMenuZip = null;
    }

    /**
     * Download and cache NickelMenu.zip (contains KoboRoot.tgz).
     */
    async loadNickelMenu(progressFn) {
        if (this.nickelMenuZip) return;
        progressFn('Downloading NickelMenu...');
        const resp = await fetchOrThrow('assets/NickelMenu.zip', 'Failed to download NickelMenu.zip');
        this.nickelMenuZip = await JSZip.loadAsync(await resp.arrayBuffer());
    }

    /**
     * Get KoboRoot.tgz from the NickelMenu zip.
     */
    async getKoboRootTgz() {
        const file = this.nickelMenuZip.file('KoboRoot.tgz');
        if (!file) throw new Error('KoboRoot.tgz not found in NickelMenu.zip');
        return new Uint8Array(await file.async('arraybuffer'));
    }

    /**
     * Run selected features and collect all files to write.
     * @param {object[]} features - feature modules to run
     * @param {function} progressFn
     * @returns {{ path: string, data: Uint8Array|string }[]}
     */
    async collectFiles(features, progressFn, deviceInfo = null, { menuCustomization = null } = {}) {
        let files = [];
        const featureFiles = {};

        // Run install() for features that have it
        for (const feature of features) {
            if (!feature.install) continue;
            const ctx = createContext(feature, progressFn, deviceInfo, features, menuCustomization);
            progressFn(`Setting up ${feature.title}...`);
            const result = await feature.install(ctx);
            files.push(...result);
            featureFiles[feature.id] = result.map(f => f.path);
        }

        // De-duplicate shared install files by path — e.g. several home-content
        // hiders each ship the identical toggle script. Keep the first write.
        const seenPaths = new Set();
        files = files.filter(file => {
            if (seenPaths.has(file.path)) return false;
            seenPaths.add(file.path);
            return true;
        });

        // Assemble the NickelMenu items file from the features' menuItems hooks.
        const itemsContent = buildItemsFile(features, deviceInfo, menuCustomization);
        if (itemsContent !== null) {
            files.push({ path: NM_ITEMS_FILE, data: itemsContent });
        }

        // Run postProcess() for features that have it.
        const itemsFile = files.find(f => f.path === NM_ITEMS_FILE);
        for (const feature of features) {
            if (!feature.postProcess) continue;
            const ctx = createContext(feature, progressFn, deviceInfo, features, menuCustomization);
            files = feature.postProcess(files, ctx);
        }

        // Encode the items file to bytes for writing.
        if (itemsFile && typeof itemsFile.data === 'string') {
            itemsFile.data = new TextEncoder().encode(itemsFile.data);
        }

        return { files, featureFiles };
    }

    /**
     * Install to a connected Kobo device via File System Access API.
     */
    async installToDevice(device, features, progressFn, { audit = null, menuCustomization = null } = {}) {
        await this.loadNickelMenu(progressFn);

        progressFn('Writing KoboRoot.tgz...');
        const tgz = await this.getKoboRootTgz();
        await device.writeFile(['.kobo', 'KoboRoot.tgz'], tgz);
        audit?.record(`Installed NickelMenu: wrote .kobo/KoboRoot.tgz (${tgz.length} bytes)`);

        let collectedFiles = [];
        let featureFiles = {};

        if (features.length > 0) {
            progressFn('Updating Kobo eReader.conf...');
            await this.updateEReaderConf(device, features, audit);

            const result = await this.collectFiles(features, progressFn, device.deviceInfo, { menuCustomization });
            collectedFiles = result.files;
            featureFiles = result.featureFiles;

            progressFn('Writing files to Kobo...');
            const totalFiles = collectedFiles.length;
            for (let i = 0; i < collectedFiles.length; i++) {
                const { path, data } = collectedFiles[i];
                const pathArray = path.split('/');
                const fileData = typeof data === 'string' ? new TextEncoder().encode(data) : data;
                await device.writeFile(pathArray, fileData);
                audit?.record(`Wrote ${path} (${fileData.length} bytes)`);
                progressFn(`Writing files to Kobo (${i + 1} of ${totalFiles})...`);
            }
        }

        // Write the install manifest
        const manifest = this.buildManifest(features, collectedFiles, featureFiles, device.deviceInfo, audit);
        if (manifest) {
            await this.writeManifest(device, manifest);
        }

        await writeAuditLog(audit, device);
        progressFn('Done.');
    }

    /**
     * Build a zip for manual download.
     */
    async buildDownloadZip(features, progressFn, deviceInfo = null, { menuCustomization = null } = {}) {
        await this.loadNickelMenu(progressFn);

        progressFn('Building download package...');
        const zip = new JSZip();

        const tgz = await this.getKoboRootTgz();
        zip.file('.kobo/KoboRoot.tgz', tgz);

        let collectedFiles = [];
        let featureFiles = {};

        if (features.length > 0) {
            const result = await this.collectFiles(features, progressFn, deviceInfo, { menuCustomization });
            collectedFiles = result.files;
            featureFiles = result.featureFiles;
            for (const { path, data } of collectedFiles) {
                const fileData = typeof data === 'string' ? new TextEncoder().encode(data) : data;
                zip.file(path, fileData);
            }
        }

        // Include the install manifest so the downloaded archive carries the same
        // definitional info about the chosen features that a USB install writes.
        const manifest = this.buildManifest(features, collectedFiles, featureFiles, deviceInfo, null);
        if (manifest) {
            const data = new TextEncoder().encode(JSON.stringify(manifest, null, 2) + '\n');
            zip.file(`${AUDIT_LOG_DIRECTORY}/nickelmenu.json`, data);
        }

        progressFn('Compressing...');
        const result = await zip.generateAsync({ type: 'uint8array' });
        progressFn('Done.');
        return result;
    }

    /**
     * Add or update ExcludeSyncFolders in Kobo eReader.conf.
     * @param {object[]} features - selected features; if 'exclude-calibre' is included, the calibre folder is excluded.
     */
    async updateEReaderConf(device, features = [], audit = null) {
        const confPath = ['.kobo', 'Kobo', 'Kobo eReader.conf'];
        const settingLine = getExcludeSyncFoldersLine(features);
        let content = setExcludeSyncFoldersLine(
            await device.readFile(confPath) || '',
            settingLine
        );
        audit?.record(`Set Kobo eReader.conf ExcludeSyncFolders=${settingLine}`);

        // Apply any Kobo eReader.conf settings declared by selected features
        // (e.g. better-typography's reading/rendering preferences). Features pass
        // the full selection so they can adapt (e.g. only set a default font when
        // the fonts are also being installed).
        const settingsCtx = { deviceInfo: device.deviceInfo, features };
        for (const feature of features) {
            if (!feature.confSettings) continue;
            for (const { section, key, value } of feature.confSettings(settingsCtx)) {
                content = setConfSetting(content, section, key, value);
                audit?.record(`Set Kobo eReader.conf [${section}] ${key}=${value}`);
            }
        }

        await device.writeFile(confPath, new TextEncoder().encode(content));
    }

    /**
     * Remove ExcludeSyncFolders from Kobo eReader.conf.
     */
    async removeExcludeSyncFolders(device) {
        const confPath = ['.kobo', 'Kobo', 'Kobo eReader.conf'];
        const content = await device.readFile(confPath);
        if (!content || !content.includes('ExcludeSyncFolders')) return;

        const updated = removeExcludeSyncFoldersLine(content);
        if (updated !== content) {
            await device.writeFile(confPath, new TextEncoder().encode(updated));
        }
    }

    /**
     * Replace legacy malformed ExcludeSyncFolders values with the default
     * generated line when uninstall keeps sync exclusions in place.
     */
    async repairLegacyExcludeSyncFolders(device) {
        const confPath = ['.kobo', 'Kobo', 'Kobo eReader.conf'];
        const content = await device.readFile(confPath);
        if (!content || !content.includes('ExcludeSyncFolders')) return;

        let updated = content;
        for (const line of Object.values(legacyBrokenExcludeSyncFoldersLines)) {
            if (!updated.includes(line)) continue;
            updated = setExcludeSyncFoldersLine(updated, buildExcludeSyncFoldersLine());
        }

        if (updated !== content) {
            await device.writeFile(confPath, new TextEncoder().encode(updated));
        }
    }

    buildManifest(features, collectedFiles, featureFiles, deviceInfo, audit) {
        const selected = features.map(f => f.id);
        const settingsCtx = { deviceInfo, features };
        const manifestFeatures = {};

        for (const feature of features) {
            const entry = {};

            if (feature.directories) {
                entry.directories = feature.directories;
            } else {
                entry.files = [];
                const paths = featureFiles[feature.id] || [];
                for (const path of paths) {
                    entry.files.push({ path, type: 'file' });
                }
            }

            if (feature.confSettings) {
                const conf = feature.confSettings(settingsCtx)
                    .filter(s => s.revertable)
                    .map(s => ({ section: s.section, key: s.key, value: s.value, revertTo: s.revertTo ?? null }));
                if (conf.length > 0) entry.conf = conf;
            }

            manifestFeatures[feature.id] = entry;
        }

        const version = (typeof globalThis.__APP_VERSION__ !== 'undefined' ? globalThis.__APP_VERSION__ : null) || 'unknown';
        const timestamp = audit ? audit.startedAt.toISOString() : new Date().toISOString();
        const firmware = deviceInfo?.firmware || null;
        const model = deviceInfo?.serialPrefix || deviceInfo?.model || null;

        return {
            selected,
            features: manifestFeatures,
            meta: {
                writer: { name: 'kobopatch-webui', version },
                installed: { timestamp, firmware, model },
            },
        };
    }

    async writeManifest(device, manifest) {
        const data = new TextEncoder().encode(JSON.stringify(manifest, null, 2) + '\n');
        await device.writeFile([AUDIT_LOG_DIRECTORY, 'nickelmenu.json'], data);
    }
}
