/**
 * BackupStep.js — `step-nm-backup`, the optional pre-install backup of the
 * device's key files, and the "keep my existing NickelMenu config" question.
 */

import { $qa, requireButton, requireElement, requireInput } from '../../shell/dom.js';
import { prepareNmBackup, shouldOfferNmBackup } from '../nickelmenu-backup.js';
import { NickelMenuStep } from './NickelMenuStep.js';

const BACKUP_INTRO_AUTOMATIC =
    "Before continuing, it's highly recommended that you let the Web UI make an automatic backup of important system files. You can do that here.";
const BACKUP_INTRO_MANUAL = 'Manual mode cannot create a backup for you, but it is worth making a backup of some important device files first.';
const KEEP_CONFIG_TITLE_OURS = 'Keep previous KoboPatch Web UI config (not recommended)';
const KEEP_CONFIG_TITLE_THEIRS = 'Keep my custom NickelMenu configuration';
const KEEP_CONFIG_DESC_OURS =
    'This appears to be from an earlier KoboPatch Web UI installation. Since the new config will include the same entries, you can safely leave this unchecked and the old file will be cleaned up. If you made manual modifications to the file, you may want to check this box.';
const KEEP_CONFIG_DESC_THEIRS =
    'This appears to be a NickelMenu config that was not generated by this tool. Keep this checked to preserve your manual entries alongside the new config.';

export class BackupStep extends NickelMenuStep {
    /** @param {import('./NickelMenuFlow.js').NickelMenuFlow} owner */
    constructor(owner) {
        super(owner, { id: 'backup', domId: 'step-nm-backup', navIndex: 4 });

        this.root = requireElement('step-nm-backup');
        this.btnBack = requireButton('btn-nm-backup-back');
        this.btnNext = requireButton('btn-nm-backup-next');
        this.intro = requireElement('nm-backup-intro');
        this.options = requireElement('nm-backup-options');
        this.localNote = requireElement('nm-backup-local-note');
        this.manualInstructions = requireElement('nm-manual-backup-instructions');
        this.keepConfigOption = requireElement('nm-keep-config-option');
        this.keepConfigCheckbox = requireInput('nm-keep-items');
        this.keepConfigTitle = requireElement('nm-keep-config-title');
        this.keepConfigDesc = requireElement('nm-keep-config-desc');

        this.#wireListeners();
    }

    back(_ctx) {
        return this.owner.selection.option === 'preset' ? 'features' : 'config';
    }

    async onEnter(_ctx) {
        const session = this.session;
        const selection = this.owner.selection;
        const canCreateBackup = shouldOfferNmBackup(session);
        if (canCreateBackup && !selection.backupChoice) {
            selection.backupChoice = 'key-files';
            for (const radio of this.#backupRadios()) {
                const checked = radio.value === selection.backupChoice;
                radio.checked = checked;
                radio.closest('.selection-card')?.classList.toggle('selection-card--selected', checked);
            }
        }

        this.btnNext.disabled = canCreateBackup ? !selection.backupChoice : false;
        this.btnBack.disabled = false;
        this.btnNext.textContent = 'Continue \u203A';
        this.intro.textContent = canCreateBackup ? BACKUP_INTRO_AUTOMATIC : BACKUP_INTRO_MANUAL;
        this.options.hidden = !canCreateBackup;
        this.localNote.hidden = !canCreateBackup;
        this.manualInstructions.hidden = canCreateBackup;

        const detected = this.owner.detected;
        if (detected.legacyItemsDetected && selection.option === 'preset') {
            this.keepConfigCheckbox.checked = detected.legacyItemsWasOurs ? false : true;
            selection.keepLegacyConfig = this.keepConfigCheckbox.checked;
            this.keepConfigTitle.textContent = detected.legacyItemsWasOurs ? KEEP_CONFIG_TITLE_OURS : KEEP_CONFIG_TITLE_THEIRS;
            this.keepConfigDesc.textContent = detected.legacyItemsWasOurs ? KEEP_CONFIG_DESC_OURS : KEEP_CONFIG_DESC_THEIRS;
            this.keepConfigOption.hidden = false;
        } else {
            this.keepConfigOption.hidden = true;
        }
    }

    reset() {
        this.btnNext.disabled = true;
        this.btnNext.textContent = 'Continue \u203A';
        this.btnBack.disabled = false;
        for (const radio of this.#backupRadios()) {
            radio.checked = false;
            radio.closest('.selection-card')?.classList.remove('selection-card--selected');
            radio.disabled = false;
        }
    }

    #backupRadios() {
        return $qa('input[name="nm-backup-option"]', this.root);
    }

    #wireListeners() {
        for (const radio of this.#backupRadios()) {
            radio.addEventListener(
                'change',
                () => {
                    this.owner.selection.backupChoice = radio.value;
                    this.btnNext.disabled = false;
                    for (const other of this.#backupRadios()) {
                        other.closest('.selection-card')?.classList.toggle('selection-card--selected', other.checked);
                    }
                },
                { signal: this.listeners.signal },
            );
        }

        this.keepConfigCheckbox.addEventListener(
            'change',
            () => {
                this.owner.selection.keepLegacyConfig = this.keepConfigCheckbox.checked;
            },
            { signal: this.listeners.signal },
        );

        this.btnBack.addEventListener(
            'click',
            async () => {
                await this.owner.goBack();
            },
            { signal: this.listeners.signal },
        );

        this.btnNext.addEventListener(
            'click',
            async () => {
                const session = this.session;
                const selection = this.owner.selection;
                if (!shouldOfferNmBackup(session)) {
                    await this.owner.go('review');
                    return;
                }

                if (!selection.backupChoice) return;
                if (selection.backupChoice === 'skip') {
                    await this.owner.go('review');
                    return;
                }

                this.btnBack.disabled = true;
                this.btnNext.disabled = true;
                this.btnNext.textContent = 'Preparing backup...';
                for (const radio of this.#backupRadios()) {
                    radio.disabled = true;
                }

                try {
                    const backup = await prepareNmBackup(session);
                    if (backup) {
                        await this.owner.terminal.download({ entries: backup.entries, filename: backup.filename });
                    }
                    await this.owner.go('review');
                } catch (err) {
                    this.nav.showError(err.message);
                } finally {
                    this.btnBack.disabled = false;
                    this.btnNext.textContent = 'Continue \u203A';
                    for (const radio of this.#backupRadios()) {
                        radio.disabled = false;
                    }
                }
            },
            { signal: this.listeners.signal },
        );
    }
}
