import test from 'node:test';
import assert from 'node:assert/strict';

import {
    buildNickelMenuInstructions,
    buildPatchesInstructions,
    CONF_DESC_DEFAULT,
    CONF_DESC_EXCLUDE_CALIBRE,
    KOBO_RESET_HELP_URL,
} from '../../src/js/shell/instructions.js';

// A fixed timestamp so the rendered header is deterministic.
const DATE = new Date(Date.UTC(2026, 5, 14, 13, 45));

test('NickelMenu instructions include the credit header with version and date', () => {
    const text = buildNickelMenuInstructions({ version: '1.2.3', date: DATE, isPreset: false });
    assert.match(text, /Generated by KoboPatch Web UI \(version 1\.2\.3\) on 2026-06-14 13:45 UTC\./);
    assert.match(text, /github\.com\/nicoverbruggen\/kobopatch-webui/);
});

test('NickelMenu instructions include the hard-lock disclaimer and Kobo reset link', () => {
    const text = buildNickelMenuInstructions({ version: '1.0.0', date: DATE, isPreset: false });
    assert.match(text, /reset your Kobo/);
    assert.match(text, /hard-locked/);
    assert.ok(text.includes(KOBO_RESET_HELP_URL));
});

test('NickelMenu non-preset instructions omit the config steps', () => {
    const text = buildNickelMenuInstructions({ version: '1.0.0', date: DATE, isPreset: false });
    assert.ok(!text.includes('Kobo eReader.conf'));
    // Connect, extract, eject — the three universal steps.
    assert.match(text, /^1\. Connect your Kobo via USB/m);
    assert.match(text, /^2\. Extract the downloaded ZIP/m);
    assert.match(text, /^3\. Safely eject the Kobo/m);
    assert.match(text, /install NickelMenu automatically\./);
});

test('NickelMenu preset instructions add the ExcludeSyncFolders config step', () => {
    const text = buildNickelMenuInstructions({
        version: '1.0.0',
        date: DATE,
        isPreset: true,
        confLine: 'ExcludeSyncFolders=\\.(?!kobo|adds).*',
        hasExcludeCalibre: false,
    });
    assert.match(text, /Open \.kobo\/Kobo\/Kobo eReader\.conf in a text editor\./);
    assert.ok(text.includes('ExcludeSyncFolders=\\.(?!kobo|adds).*'));
    assert.ok(text.includes(CONF_DESC_DEFAULT));
    // Reboot-for-config step is present for preset installs.
    assert.match(text, /Powered off/);
});

test('NickelMenu preset instructions use the calibre description when excluding calibre', () => {
    const text = buildNickelMenuInstructions({
        version: '1.0.0',
        date: DATE,
        isPreset: true,
        confLine: 'ExcludeSyncFolders=x',
        hasExcludeCalibre: true,
    });
    assert.ok(text.includes(CONF_DESC_EXCLUDE_CALIBRE));
    assert.ok(!text.includes(CONF_DESC_DEFAULT));
});

test('NickelMenu preset instructions render feature conf settings grouped by section', () => {
    const text = buildNickelMenuInstructions({
        version: '1.0.0',
        date: DATE,
        isPreset: true,
        confLine: 'ExcludeSyncFolders=x',
        confSettings: [
            { section: 'Reading', key: 'ReadingFontFamily', value: 'Kobo Nia' },
            { section: 'Reading', key: 'ReadingFontSize', value: '22' },
        ],
    });
    assert.match(text, /In the \[Reading\] section \(add it if it is missing\):/);
    assert.ok(text.includes('ReadingFontFamily=Kobo Nia'));
    assert.ok(text.includes('ReadingFontSize=22'));
});

test('NickelMenu steps are numbered sequentially regardless of which are present', () => {
    const text = buildNickelMenuInstructions({
        version: '1.0.0',
        date: DATE,
        isPreset: true,
        confLine: 'ExcludeSyncFolders=x',
        confSettings: [{ section: 'Reading', key: 'A', value: 'b' }],
    });
    // 1 connect, 2 conf line, 3 conf settings, 4 reboot, 5 extract, 6 eject.
    for (const n of [1, 2, 3, 4, 5, 6]) {
        assert.match(text, new RegExp(`^${n}\\. `, 'm'));
    }
    assert.ok(!/^7\. /m.test(text));
});

test('patches instructions include the device name, header, and disclaimer', () => {
    const text = buildPatchesInstructions({ version: '2.0.0', date: DATE, deviceName: 'Kobo Libra Color' });
    assert.match(text, /Generated by KoboPatch Web UI \(version 2\.0\.0\) on 2026-06-14 13:45 UTC\./);
    assert.match(text, /^1\. Connect your Kobo Libra Color via USB/m);
    assert.match(text, /apply the patches automatically\./);
    assert.ok(text.includes(KOBO_RESET_HELP_URL));
});

test('patches instructions fall back to "Kobo" when no device name is given', () => {
    const text = buildPatchesInstructions({ version: '2.0.0', date: DATE });
    assert.match(text, /^1\. Connect your Kobo via USB/m);
});
