import test from 'node:test';
import assert from 'node:assert/strict';

import JSZip from 'jszip';

import { NM_ITEMS_FILE } from '../../src/js/nickelmenu/constants.js';
import { NickelMenuInstaller } from '../../src/js/nickelmenu/installer.js';
import { AuditLog } from '../../src/js/kobo/audit-log.js';
import customMenu from '../../src/js/nickelmenu/features/custom-menu/index.js';
import excludeCalibre from '../../src/js/nickelmenu/features/exclude-calibre/index.js';
import { homeHiders } from '../../src/js/nickelmenu/features/hide-home-content/index.js';
import {
    RecordingDevice,
    bytes,
    createInstaller,
    createProgressRecorder,
    koboEReaderConfPath,
    koboRootTgzPath,
    text,
    useCustomMenuAssetFetch,
} from './test-helpers.js';

const hideNotices = homeHiders.find(f => f.id === 'hide-notices');

test('installToDevice with no features writes NickelMenu KoboRoot.tgz and manifest', async () => {
    const tgz = bytes('tgz payload');
    const installer = createInstaller(tgz);
    const device = new RecordingDevice();
    const progress = createProgressRecorder();

    await installer.installToDevice(device, [], progress);

    assert.deepEqual(device.writePaths(), [
        koboRootTgzPath,
        '.kobopatch-webui/nickelmenu.json',
    ]);
    assert.deepEqual(device.writeFor(koboRootTgzPath).data, tgz);
    // Manifest should record no selected features
    const manifest = JSON.parse(text(device.writeFor('.kobopatch-webui/nickelmenu.json').data));
    assert.deepEqual(manifest.selected, []);
    assert.deepEqual(manifest.features, {});
    assert.equal(manifest.meta.writer.name, 'kobopatch-webui');
    assert.equal(manifest.meta.writer.version, 'unknown');
    assert.equal(manifest.meta.installed.firmware, null);
    assert.deepEqual(progress.messages, [
        'Writing KoboRoot.tgz...',
        'Done.',
    ]);
});

test('installToDevice with features updates eReader config and writes feature files', async () => {
    const restoreFetch = useCustomMenuAssetFetch();
    const installer = createInstaller();
    const device = new RecordingDevice({
        textFiles: {
            [koboEReaderConfPath]: '[ApplicationPreferences]\nCurrentLocale=en_US\n',
        },
    });

    try {
        await installer.installToDevice(device, [customMenu], createProgressRecorder());
    } finally {
        restoreFetch();
    }

    assert.deepEqual(device.writePaths(), [
        koboRootTgzPath,
        koboEReaderConfPath,
        '.adds/nm/.cog.png',
        NM_ITEMS_FILE,
        '.kobopatch-webui/nickelmenu.json',
    ]);
    assert.match(text(device.writeFor(koboEReaderConfPath).data), /^\[ApplicationPreferences\]\nCurrentLocale=en_US\n\n\[FeatureSettings\]\nExcludeSyncFolders=/);
    // The items file is generated from the feature menuItems hooks.
    const items = text(device.writeFor(NM_ITEMS_FILE).data);
    assert.match(items, /^# Generated by KoboPatch Web UI/);
    assert.match(items, /^experimental :menu_main_15505_label :Toggle\n/m);
    assert.match(items, /^menu_item :main :Screenshots/m);
    assert.match(items, /^menu_item :reader :Dark Mode/m);
    // Manifest records the selected feature and its files
    const manifest = JSON.parse(text(device.writeFor('.kobopatch-webui/nickelmenu.json').data));
    assert.deepEqual(manifest.selected, ['custom-menu']);
    assert.ok(manifest.features['custom-menu']);
    assert.ok(manifest.features['custom-menu'].files.some(f => f.path === '.adds/nm/.cog.png'));
});

test('installToDevice uses the calibre sync exclusion when exclude-calibre is selected', async () => {
    const installer = createInstaller();
    const device = new RecordingDevice();

    await installer.installToDevice(device, [excludeCalibre], createProgressRecorder());

    assert.deepEqual(device.writePaths(), [
        koboRootTgzPath,
        koboEReaderConfPath,
        '.kobopatch-webui/nickelmenu.json',
    ]);
    assert.match(
        text(device.writeFor(koboEReaderConfPath).data),
        /^ExcludeSyncFolders=\(calibre\|/m
    );
});

test('installToDevice writes post-processed NickelMenu items as bytes', async () => {
    const restoreFetch = useCustomMenuAssetFetch();
    const installer = createInstaller();
    const device = new RecordingDevice();

    try {
        await installer.installToDevice(
            device,
            [customMenu, hideNotices],
            createProgressRecorder()
        );
    } finally {
        restoreFetch();
    }

    const itemsWrite = device.writeFor(NM_ITEMS_FILE);
    assert.ok(itemsWrite.data instanceof Uint8Array);
    const items = text(itemsWrite.data);
    // hide-notices appends its flag to the generated items file
    assert.match(items, /experimental:hide_home_row3_enabled:1\n$/);
    // ...and contributes the shared home-content toggle item.
    assert.match(items, /toggle_hidden_home\.sh/);
});

test('installToDevice de-duplicates the shared home-content toggle across hiders', async () => {
    const restoreFetch = useCustomMenuAssetFetch();
    const installer = createInstaller();
    const device = new RecordingDevice();
    const hiders = homeHiders.filter(f => ['hide-recommendations', 'hide-notices'].includes(f.id));

    try {
        await installer.installToDevice(device, [customMenu, ...hiders], createProgressRecorder());
    } finally {
        restoreFetch();
    }

    // Two hiders each ship + contribute the same toggle, but it lands once.
    const scriptWrites = device.writePaths().filter(path => path.endsWith('toggle_hidden_home.sh'));
    assert.deepEqual(scriptWrites, ['.adds/nm/scripts/toggle_hidden_home.sh']);

    const items = text(device.writeFor(NM_ITEMS_FILE).data);
    const toggleCount = (items.match(/Minimal Home/g) || []).length;
    assert.equal(toggleCount, 1);
    // Both hiders' distinct flags are still appended.
    assert.match(items, /experimental:hide_home_row1col2_enabled:1/);
    assert.match(items, /experimental:hide_home_row3_enabled:1/);
});

test('installToDevice writes an audit log under .kobopatch-webui/logs when an AuditLog is passed', async () => {
    const restoreFetch = useCustomMenuAssetFetch();
    const installer = createInstaller();
    const device = new RecordingDevice();
    const audit = new AuditLog('install-nickelmenu', new Date(2026, 5, 11, 14, 30));

    try {
        await installer.installToDevice(device, [customMenu], createProgressRecorder(), { audit });
    } finally {
        restoreFetch();
    }

    const logPath = '.kobopatch-webui/logs/26-06-11_14-30-install-nickelmenu.log';
    assert.ok(device.writePaths().includes(logPath));
    const log = text(device.writeFor(logPath).data);
    assert.match(log, /wrote \.kobo\/KoboRoot\.tgz/);
    assert.match(log, /Set Kobo eReader\.conf ExcludeSyncFolders=/);
    assert.match(log, /Wrote \.adds\/nm\/webui-preset/);
});

test('installToDevice writes manifest but no audit log when none is passed', async () => {
    const restoreFetch = useCustomMenuAssetFetch();
    const installer = createInstaller();
    const device = new RecordingDevice();

    try {
        await installer.installToDevice(device, [customMenu], createProgressRecorder());
    } finally {
        restoreFetch();
    }

    // Manifest is always written; no audit log file should exist.
    assert.ok(device.writePaths().includes('.kobopatch-webui/nickelmenu.json'));
    assert.ok(!device.writePaths().some(path => path.startsWith('.kobopatch-webui/logs/')));
});

test('installToDevice stops before config or feature writes if KoboRoot.tgz write fails', async () => {
    const installer = createInstaller();
    const device = new RecordingDevice({ failWritePath: koboRootTgzPath });

    await assert.rejects(
        () => installer.installToDevice(device, [excludeCalibre], createProgressRecorder()),
        /Refusing write to \.kobo\/KoboRoot\.tgz/
    );
    assert.deepEqual(device.writePaths(), []);
});

test('installToDevice stops writing remaining feature files after a feature write fails', async () => {
    const restoreFetch = useCustomMenuAssetFetch();
    const installer = createInstaller();
    const device = new RecordingDevice({ failWritePath: '.adds/nm/.cog.png' });

    try {
        await assert.rejects(
            () => installer.installToDevice(device, [customMenu], createProgressRecorder()),
            /Refusing write to \.adds\/nm\/\.cog\.png/
        );
    } finally {
        restoreFetch();
    }
    assert.deepEqual(device.writePaths(), [
        koboRootTgzPath,
        koboEReaderConfPath,
    ]);
});

test('installToDevice does not write to the device when NickelMenu zip is missing KoboRoot.tgz', async () => {
    const installer = new NickelMenuInstaller();
    installer.nickelMenuZip = new JSZip();
    installer.nickelMenuZip.file('not-KoboRoot.tgz', bytes('wrong file'));
    const device = new RecordingDevice();

    await assert.rejects(
        () => installer.installToDevice(device, [], createProgressRecorder()),
        /KoboRoot\.tgz not found/
    );
    assert.deepEqual(device.writePaths(), []);
});

test('buildDownloadZip with no features includes only NickelMenu KoboRoot.tgz', async () => {
    const tgz = bytes('download tgz');
    const installer = createInstaller(tgz);

    const result = await installer.buildDownloadZip([], createProgressRecorder());
    const zip = await JSZip.loadAsync(result);
    const filePaths = Object.keys(zip.files).filter(path => !zip.files[path].dir);

    assert.deepEqual(filePaths, ['.kobo/KoboRoot.tgz']);
    assert.deepEqual(await zip.file('.kobo/KoboRoot.tgz').async('uint8array'), tgz);
});

test('buildDownloadZip with features includes feature files but not Kobo eReader.conf', async () => {
    const restoreFetch = useCustomMenuAssetFetch();
    const installer = createInstaller(bytes('download tgz'));

    try {
        const result = await installer.buildDownloadZip(
            [customMenu, hideNotices],
            createProgressRecorder()
        );
        const zip = await JSZip.loadAsync(result);
        const filePaths = Object.keys(zip.files).filter(path => !zip.files[path].dir);

        assert.deepEqual(filePaths, [
            '.kobo/KoboRoot.tgz',
            '.adds/nm/.cog.png',
            '.adds/nm/scripts/toggle_hidden_home.sh',
            NM_ITEMS_FILE,
        ]);
        assert.match(
            await zip.file(NM_ITEMS_FILE).async('string'),
            /experimental:hide_home_row3_enabled:1\n$/
        );
        assert.equal(zip.file(koboEReaderConfPath), null);
    } finally {
        restoreFetch();
    }
});

test('buildDownloadZip rejects when NickelMenu zip is missing KoboRoot.tgz', async () => {
    const installer = new NickelMenuInstaller();
    installer.nickelMenuZip = new JSZip();
    installer.nickelMenuZip.file('not-KoboRoot.tgz', bytes('wrong file'));

    await assert.rejects(
        () => installer.buildDownloadZip([], createProgressRecorder()),
        /KoboRoot\.tgz not found/
    );
});
