import test from 'node:test';
import assert from 'node:assert/strict';

import JSZip from 'jszip';

import { NM_ITEMS_FILE } from '../../src/js/nickelmenu/constants.js';
import { NM_MENU_ICON_CUSTOM_PNG_PATH } from '../../src/js/nickelmenu/customization.js';
import { NickelMenuInstaller } from '../../src/js/nickelmenu/installer.js';
import { buildTarGz, parseTarGz } from '../../src/js/nickelmenu/archive.js';
import { AuditLog } from '../../src/js/kobo/audit-log.js';
import customMenu from '../../src/js/nickelmenu/features/custom-menu/index.js';
import excludeCalibre from '../../src/js/nickelmenu/features/exclude-calibre/index.js';
import { homeHiders } from '../../src/js/nickelmenu/features/hide-home-content/index.js';
import {
    RecordingDevice,
    bytes,
    createInstaller,
    createProgressRecorder,
    koboEReaderConfPath,
    koboRootTgzPath,
    text,
    useCustomMenuAssetFetch,
} from './test-helpers.js';

const hideNotices = homeHiders.find(f => f.id === 'hide-notices');

test('installToDevice with no features writes NickelMenu KoboRoot.tgz and manifest', async () => {
    const tgz = bytes('tgz payload');
    const installer = createInstaller(tgz);
    const device = new RecordingDevice();
    const progress = createProgressRecorder();

    await installer.installToDevice(device, [], progress);

    assert.deepEqual(device.writePaths(), [
        '.kobopatch-webui/nickelmenu.json',
        koboRootTgzPath,
    ]);
    assert.deepEqual(device.writeFor(koboRootTgzPath).data, tgz);
    // Manifest should record no selected features
    const manifest = JSON.parse(text(device.writeFor('.kobopatch-webui/nickelmenu.json').data));
    assert.deepEqual(manifest.selected, []);
    assert.deepEqual(manifest.features, {});
    assert.equal(manifest.meta.writer.name, 'kobopatch-webui');
    assert.equal(manifest.meta.writer.version, 'unknown');
    assert.equal(manifest.meta.installed.firmware, null);
    assert.equal(manifest.meta.installed.channel, null);
    assert.deepEqual(progress.messages, [
        'Writing KoboRoot.tgz...',
        'Done.',
    ]);
});

test('installToDevice with features updates eReader config and writes feature files', async () => {
    const restoreFetch = useCustomMenuAssetFetch();
    const installer = createInstaller();
    const device = new RecordingDevice({
        textFiles: {
            [koboEReaderConfPath]: '[ApplicationPreferences]\nCurrentLocale=en_US\n',
        },
    });

    try {
        await installer.installToDevice(device, [customMenu], createProgressRecorder());
    } finally {
        restoreFetch();
    }

    assert.deepEqual(device.writePaths(), [
        koboEReaderConfPath,
        '.adds/nm/.cog.png',
        NM_ITEMS_FILE,
        '.kobopatch-webui/nickelmenu.json',
        koboRootTgzPath,
    ]);
    assert.match(text(device.writeFor(koboEReaderConfPath).data), /^\[ApplicationPreferences\]\nCurrentLocale=en_US\n\n\[FeatureSettings\]\nExcludeSyncFolders=/);
    // The items file is generated from the feature menuItems hooks.
    const items = text(device.writeFor(NM_ITEMS_FILE).data);
    assert.match(items, /^# Generated by KoboPatch Web UI/);
    assert.match(items, /^experimental :menu_main_15505_label :Toggle\n/m);
    assert.match(items, /^menu_item :main :Screenshots/m);
    assert.match(items, /^menu_item :reader :Dark Mode/m);
    // Manifest records the selected feature and its files
    const manifest = JSON.parse(text(device.writeFor('.kobopatch-webui/nickelmenu.json').data));
    assert.deepEqual(manifest.selected, ['custom-menu']);
    assert.ok(manifest.features['custom-menu']);
    assert.ok(manifest.features['custom-menu'].files.some(f => f.path === '.adds/nm/.cog.png'));
});

test('installToDevice writes customized NickelMenu tab icon and label', async () => {
    const installer = createInstaller();
    const device = new RecordingDevice();
    const png = bytes('png data');

    await installer.installToDevice(
        device,
        [customMenu],
        createProgressRecorder(),
        {
            menuCustomization: {
                label: 'Read',
                icon: { type: 'preset', id: 'spark', mimeType: 'image/png', data: png },
            },
        }
    );

    assert.ok(device.writePaths().includes(NM_MENU_ICON_CUSTOM_PNG_PATH));
    assert.ok(!device.writePaths().includes('.adds/nm/.cog.png'));
    const items = text(device.writeFor(NM_ITEMS_FILE).data);
    assert.match(items, /^experimental :menu_main_15505_label :Read$/m);
    assert.match(items, new RegExp(`^experimental :menu_main_15505_icon :/mnt/onboard/${NM_MENU_ICON_CUSTOM_PNG_PATH}$`, 'm'));
    assert.deepEqual(device.writeFor(NM_MENU_ICON_CUSTOM_PNG_PATH).data, png);
});

test('installToDevice uses the calibre sync exclusion when exclude-calibre is selected', async () => {
    const installer = createInstaller();
    const device = new RecordingDevice();

    await installer.installToDevice(device, [excludeCalibre], createProgressRecorder());

    assert.deepEqual(device.writePaths(), [
        koboEReaderConfPath,
        '.kobopatch-webui/nickelmenu.json',
        koboRootTgzPath,
    ]);
    assert.match(
        text(device.writeFor(koboEReaderConfPath).data),
        /^ExcludeSyncFolders=\(calibre\|/m
    );
});

test('installToDevice writes post-processed NickelMenu items as bytes', async () => {
    const restoreFetch = useCustomMenuAssetFetch();
    const installer = createInstaller();
    const device = new RecordingDevice();

    try {
        await installer.installToDevice(
            device,
            [customMenu, hideNotices],
            createProgressRecorder()
        );
    } finally {
        restoreFetch();
    }

    const itemsWrite = device.writeFor(NM_ITEMS_FILE);
    assert.ok(itemsWrite.data instanceof Uint8Array);
    const items = text(itemsWrite.data);
    // hide-notices appends its flag to the generated items file
    assert.match(items, /experimental:hide_home_row3_enabled:1\n$/);
    // ...and contributes the shared home-content toggle item.
    assert.match(items, /toggle_hidden_home\.sh/);
});

test('installToDevice de-duplicates the shared home-content toggle across hiders', async () => {
    const restoreFetch = useCustomMenuAssetFetch();
    const installer = createInstaller();
    const device = new RecordingDevice();
    const hiders = homeHiders.filter(f => ['hide-recommendations', 'hide-notices'].includes(f.id));

    try {
        await installer.installToDevice(device, [customMenu, ...hiders], createProgressRecorder());
    } finally {
        restoreFetch();
    }

    // Two hiders each ship + contribute the same toggle, but it lands once.
    const scriptWrites = device.writePaths().filter(path => path.endsWith('toggle_hidden_home.sh'));
    assert.deepEqual(scriptWrites, ['.adds/nm/scripts/toggle_hidden_home.sh']);

    const items = text(device.writeFor(NM_ITEMS_FILE).data);
    const toggleCount = (items.match(/Minimal Home/g) || []).length;
    assert.equal(toggleCount, 1);
    // Both hiders' distinct flags are still appended.
    assert.match(items, /experimental:hide_home_row1col2_enabled:1/);
    assert.match(items, /experimental:hide_home_row3_enabled:1/);
});

test('install fetches the shared home-content toggle script only once across hiders', async () => {
    const originalFetch = globalThis.fetch;
    const toggleUrl = 'js/nickelmenu/features/hide-home-content/scripts/toggle_hidden_home.sh';
    const assets = {
        'js/nickelmenu/features/custom-menu/.cog.png': 'cog png',
        [toggleUrl]: '#!/bin/sh\ntoggle home',
    };
    const fetchCounts = new Map();
    globalThis.fetch = async (url) => {
        fetchCounts.set(url, (fetchCounts.get(url) || 0) + 1);
        if (!(url in assets)) return { ok: false, status: 404 };
        return {
            ok: true,
            status: 200,
            async arrayBuffer() {
                const data = bytes(assets[url]);
                return data.buffer.slice(data.byteOffset, data.byteOffset + data.byteLength);
            },
        };
    };

    const installer = createInstaller();
    const device = new RecordingDevice();
    try {
        // All three hiders selected — each ships the same toggle script.
        await installer.installToDevice(device, [customMenu, ...homeHiders], createProgressRecorder());
    } finally {
        globalThis.fetch = originalFetch;
    }

    // The per-run asset cache collapses the three identical fetches into one.
    assert.equal(fetchCounts.get(toggleUrl), 1);
    // ...and the script is still written exactly once.
    const scriptWrites = device.writePaths().filter(path => path.endsWith('toggle_hidden_home.sh'));
    assert.deepEqual(scriptWrites, ['.adds/nm/scripts/toggle_hidden_home.sh']);
});

test('installToDevice writes an audit log under .kobopatch-webui/logs when an AuditLog is passed', async () => {
    const restoreFetch = useCustomMenuAssetFetch();
    const installer = createInstaller();
    const device = new RecordingDevice();
    const audit = new AuditLog('install-nickelmenu', new Date(2026, 5, 11, 14, 30));

    try {
        await installer.installToDevice(device, [customMenu], createProgressRecorder(), { audit });
    } finally {
        restoreFetch();
    }

    const logPath = '.kobopatch-webui/logs/26-06-11_14-30-install-nickelmenu.log';
    assert.ok(device.writePaths().includes(logPath));
    const log = text(device.writeFor(logPath).data);
    assert.match(log, /wrote \.kobo\/KoboRoot\.tgz/);
    assert.match(log, /Set Kobo eReader\.conf ExcludeSyncFolders=/);
    assert.match(log, /Wrote \.adds\/nm\/webui-preset/);
});

test('installToDevice writes manifest but no audit log when none is passed', async () => {
    const restoreFetch = useCustomMenuAssetFetch();
    const installer = createInstaller();
    const device = new RecordingDevice();

    try {
        await installer.installToDevice(device, [customMenu], createProgressRecorder());
    } finally {
        restoreFetch();
    }

    // Manifest is always written; no audit log file should exist.
    assert.ok(device.writePaths().includes('.kobopatch-webui/nickelmenu.json'));
    assert.ok(!device.writePaths().some(path => path.startsWith('.kobopatch-webui/logs/')));
});

test('installToDevice writes KoboRoot.tgz last', async () => {
    const restoreFetch = useCustomMenuAssetFetch();
    const installer = createInstaller();
    const device = new RecordingDevice();

    try {
        await installer.installToDevice(device, [customMenu], createProgressRecorder());
    } finally {
        restoreFetch();
    }

    assert.equal(device.writePaths().at(-1), koboRootTgzPath);
});

test('installToDevice stops after preceding writes if final KoboRoot.tgz write fails', async () => {
    const installer = createInstaller();
    const device = new RecordingDevice({ failWritePath: koboRootTgzPath });

    await assert.rejects(
        () => installer.installToDevice(device, [excludeCalibre], createProgressRecorder()),
        /Refusing write to \.kobo\/KoboRoot\.tgz/
    );
    assert.deepEqual(device.writePaths(), [
        koboEReaderConfPath,
        '.kobopatch-webui/nickelmenu.json',
    ]);
});

test('installToDevice stops before config overwrite when Kobo eReader.conf cannot be read', async () => {
    const installer = createInstaller();
    const device = new RecordingDevice({
        textFiles: {
            [koboEReaderConfPath]: '[General]\nsome=setting\n',
        },
        failReadPaths: [koboEReaderConfPath],
    });

    await assert.rejects(
        () => installer.installToDevice(device, [excludeCalibre], createProgressRecorder()),
        /Refusing read of \.kobo\/Kobo\/Kobo eReader\.conf/
    );
    assert.deepEqual(device.writePaths(), []);
    assert.equal(device.writeFor(koboEReaderConfPath), undefined);
});

test('installToDevice stops writing remaining feature files after a feature write fails', async () => {
    const restoreFetch = useCustomMenuAssetFetch();
    const installer = createInstaller();
    const device = new RecordingDevice({ failWritePath: '.adds/nm/.cog.png' });

    try {
        await assert.rejects(
            () => installer.installToDevice(device, [customMenu], createProgressRecorder()),
            /Refusing write to \.adds\/nm\/\.cog\.png/
        );
    } finally {
        restoreFetch();
    }
    assert.deepEqual(device.writePaths(), [
        koboEReaderConfPath,
    ]);
});

test('installToDevice does not write to the device when NickelMenu zip is missing KoboRoot.tgz', async () => {
    const installer = new NickelMenuInstaller();
    installer.nickelMenuZip = new JSZip();
    installer.nickelMenuZip.file('not-KoboRoot.tgz', bytes('wrong file'));
    const device = new RecordingDevice();

    await assert.rejects(
        () => installer.installToDevice(device, [], createProgressRecorder()),
        /KoboRoot\.tgz not found/
    );
    assert.deepEqual(device.writePaths(), []);
});

test('buildDownloadZip with no features includes NickelMenu KoboRoot.tgz and manifest', async () => {
    const tgz = bytes('download tgz');
    const installer = createInstaller(tgz);

    const result = await installer.buildDownloadZip([], createProgressRecorder());
    const zip = await JSZip.loadAsync(result);
    const filePaths = Object.keys(zip.files).filter(path => !zip.files[path].dir);

    assert.deepEqual(filePaths, ['.kobo/KoboRoot.tgz', '.kobopatch-webui/nickelmenu.json', 'instructions.txt']);
    assert.deepEqual(await zip.file('.kobo/KoboRoot.tgz').async('uint8array'), tgz);

    const manifest = JSON.parse(await zip.file('.kobopatch-webui/nickelmenu.json').async('string'));
    assert.deepEqual(manifest.selected, []);

    // No preset chosen → no config steps, but the credit header and disclaimer
    // are always present.
    const instructions = await zip.file('instructions.txt').async('string');
    assert.match(instructions, /Generated by KoboPatch Web UI/);
    assert.match(instructions, /reset your Kobo/);
    assert.ok(!instructions.includes('Kobo eReader.conf'));
});

test('buildDownloadZip with features includes feature files but not Kobo eReader.conf', async () => {
    const restoreFetch = useCustomMenuAssetFetch();
    const installer = createInstaller(bytes('download tgz'));

    try {
        const result = await installer.buildDownloadZip(
            [customMenu, hideNotices],
            createProgressRecorder()
        );
        const zip = await JSZip.loadAsync(result);
        const filePaths = Object.keys(zip.files).filter(path => !zip.files[path].dir);

        assert.deepEqual(filePaths, [
            '.kobo/KoboRoot.tgz',
            '.adds/nm/.cog.png',
            '.adds/nm/scripts/toggle_hidden_home.sh',
            NM_ITEMS_FILE,
            '.kobopatch-webui/nickelmenu.json',
            'instructions.txt',
        ]);
        assert.match(
            await zip.file(NM_ITEMS_FILE).async('string'),
            /experimental:hide_home_row3_enabled:1\n$/
        );
        assert.equal(zip.file(koboEReaderConfPath), null);

        // A preset install (features present) gets the ExcludeSyncFolders
        // config step in its bundled instructions.
        const instructions = await zip.file('instructions.txt').async('string');
        assert.match(instructions, /Kobo eReader\.conf/);
        assert.match(instructions, /ExcludeSyncFolders=/);
    } finally {
        restoreFetch();
    }
});

test('buildDownloadZip rejects when NickelMenu zip is missing KoboRoot.tgz', async () => {
    const installer = new NickelMenuInstaller();
    installer.nickelMenuZip = new JSZip();
    installer.nickelMenuZip.file('not-KoboRoot.tgz', bytes('wrong file'));

    await assert.rejects(
        () => installer.buildDownloadZip([], createProgressRecorder()),
        /KoboRoot\.tgz not found/
    );
});

// --- KoboRoot.tgz merging (the generic koboRootEntries hook) ---

const nmTgzEntry = { path: 'usr/local/Kobo/imageformats/libnm.so', data: bytes('nm plugin'), mode: 0o755 };

// A feature that contributes its own KoboRoot.tgz payload, like NickelClock.
const tgzAddonFeature = {
    id: 'tgz-addon',
    title: 'Tgz Addon',
    async koboRootEntries() {
        return [
            { path: 'usr/local/Kobo/imageformats/libaddon.so', data: bytes('addon plugin'), mode: 0o755 },
            { path: 'mnt/onboard/.adds/addon/uninstall', data: bytes('marker'), mode: 0o644 },
        ];
    },
};

async function createInstallerWithBaseTgz() {
    const installer = new NickelMenuInstaller();
    installer.nickelMenuZip = new JSZip();
    installer.nickelMenuZip.file('KoboRoot.tgz', await buildTarGz([nmTgzEntry]));
    return installer;
}

test('buildKoboRootTgz returns the base tgz verbatim when no feature contributes entries', async () => {
    const tgz = bytes('opaque base tgz');
    const installer = createInstaller(tgz);

    const result = await installer.buildKoboRootTgz([excludeCalibre], createProgressRecorder());
    assert.deepEqual(result, tgz);
});

test('buildKoboRootTgz merges a feature koboRootEntries payload into one archive', async () => {
    const installer = await createInstallerWithBaseTgz();

    const merged = await installer.buildKoboRootTgz([tgzAddonFeature], createProgressRecorder());
    const entries = await parseTarGz(merged);

    assert.deepEqual(entries.map(e => e.path), [
        'usr/local/Kobo/imageformats/libnm.so',
        'usr/local/Kobo/imageformats/libaddon.so',
        'mnt/onboard/.adds/addon/uninstall',
    ]);
    // Executable bits on both plugins are preserved through the rebuild.
    assert.equal(entries.find(e => e.path.endsWith('libnm.so')).mode, 0o755);
    assert.equal(entries.find(e => e.path.endsWith('libaddon.so')).mode, 0o755);
    assert.deepEqual(entries.find(e => e.path.endsWith('uninstall')).data, bytes('marker'));
});

test('installToDevice writes the merged KoboRoot.tgz when a tgz-addon feature is selected', async () => {
    const installer = await createInstallerWithBaseTgz();
    const device = new RecordingDevice();

    await installer.installToDevice(device, [tgzAddonFeature], createProgressRecorder());

    const written = device.writeFor(koboRootTgzPath);
    const entries = await parseTarGz(written.data);
    assert.ok(entries.some(e => e.path.endsWith('libnm.so')));
    assert.ok(entries.some(e => e.path.endsWith('libaddon.so')));
});
