import test from 'node:test';
import assert from 'node:assert/strict';

import JSZip from 'jszip';

import { NM_ITEMS_FILE, NICKELHOME_CONFIG_FILE } from '../../src/js/nickelmenu/constants.js';
import { NM_MENU_ICON_CUSTOM_PNG_PATH } from '../../src/js/nickelmenu/customization.js';
import { NickelMenuInstaller } from '../../src/js/nickelmenu/installer.js';
import { buildTarGz, parseTarGz } from '../../src/js/nickelmenu/archive.js';
import { AuditLog } from '../../src/js/kobo/audit-log.js';
import customMenu, { CUSTOM_MENU_ICON_URL, TOGGLE_SCREENSHOTS_SCRIPT_URL } from '../../src/js/nickelmenu/features/custom-menu/index.js';
import excludeCalibre from '../../src/js/nickelmenu/features/exclude-calibre/index.js';
import { homeHiders, TOGGLE_HIDDEN_HOME_SCRIPT_URL } from '../../src/js/nickelmenu/features/hide-home-content/index.js';
import {
    RecordingDevice,
    bytes,
    createInstaller,
    createProgressRecorder,
    koboEReaderConfPath,
    koboRootTgzPath,
    text,
    useCustomMenuAssetFetch,
} from './test-helpers.js';

const hideNotices = homeHiders.find((f) => f.id === 'hide-notices');

test('installToDevice with no features writes NickelMenu KoboRoot.tgz and manifest', async () => {
    const tgz = bytes('tgz payload');
    const installer = createInstaller(tgz);
    const device = new RecordingDevice();
    const progress = createProgressRecorder();

    await installer.installToDevice(device, [], progress);

    assert.deepEqual(device.writePaths(), ['.kobopatch-webui/nickelmenu.json', koboRootTgzPath]);
    assert.deepEqual(device.writeFor(koboRootTgzPath).data, tgz);
    // Manifest should record no selected features
    const manifest = JSON.parse(text(device.writeFor('.kobopatch-webui/nickelmenu.json').data));
    assert.deepEqual(manifest.selected, []);
    assert.deepEqual(manifest.features, {});
    assert.equal(manifest.meta.writer.name, 'kobopatch-webui');
    assert.equal(manifest.meta.writer.version, 'unknown');
    assert.equal(manifest.meta.installed.firmware, null);
    assert.equal(manifest.meta.installed.channel, null);
    assert.deepEqual(progress.messages, ['Writing KoboRoot.tgz...', 'Done.']);
});

test('installToDevice with features updates eReader config and writes feature files', async () => {
    const restoreFetch = useCustomMenuAssetFetch();
    const installer = createInstaller();
    const device = new RecordingDevice({
        textFiles: {
            [koboEReaderConfPath]: '[ApplicationPreferences]\nCurrentLocale=en_US\n',
        },
    });

    try {
        await installer.installToDevice(device, [customMenu], createProgressRecorder());
    } finally {
        restoreFetch();
    }

    assert.deepEqual(device.writePaths(), [
        koboEReaderConfPath,
        '.adds/nm/.cog.png',
        '.adds/nm/scripts/toggle_screenshots.sh',
        NM_ITEMS_FILE,
        '.kobopatch-webui/nickelmenu.json',
        koboRootTgzPath,
    ]);
    assert.match(
        text(device.writeFor(koboEReaderConfPath).data),
        /^\[ApplicationPreferences\]\nCurrentLocale=en_US\n\n\[FeatureSettings\]\nExcludeSyncFolders=/,
    );
    // The items file is generated from the feature menuItems hooks.
    const items = text(device.writeFor(NM_ITEMS_FILE).data);
    assert.match(items, /^# Generated by KoboPatch Web UI/);
    assert.match(items, /^experimental :menu_main_15505_label :Toggle\n/m);
    assert.match(items, /^menu_item :main :Screenshots/m);
    assert.match(items, /chain_success :cmd_output :1000 :\/mnt\/onboard\/\.adds\/nm\/scripts\/toggle_screenshots\.sh/);
    assert.match(items, /^menu_item :reader :Dark Mode/m);
    // Manifest records the selected feature and its files
    const manifest = JSON.parse(text(device.writeFor('.kobopatch-webui/nickelmenu.json').data));
    assert.deepEqual(manifest.selected, ['custom-menu']);
    assert.ok(manifest.features['custom-menu']);
    assert.ok(manifest.features['custom-menu'].files.some((f) => f.path === '.adds/nm/.cog.png'));
    assert.ok(manifest.features['custom-menu'].files.some((f) => f.path === '.adds/nm/scripts/toggle_screenshots.sh'));
});

test('installToDevice writes customized NickelMenu tab icon and label', async () => {
    const restoreFetch = useCustomMenuAssetFetch();
    const installer = createInstaller();
    const device = new RecordingDevice();
    const png = bytes('png data');

    try {
        await installer.installToDevice(device, [customMenu], createProgressRecorder(), {
            menuCustomization: {
                label: 'Read',
                icon: { type: 'preset', id: 'spark', mimeType: 'image/png', data: png },
            },
        });
    } finally {
        restoreFetch();
    }

    assert.ok(device.writePaths().includes(NM_MENU_ICON_CUSTOM_PNG_PATH));
    assert.ok(!device.writePaths().includes('.adds/nm/.cog.png'));
    const items = text(device.writeFor(NM_ITEMS_FILE).data);
    assert.match(items, /^experimental :menu_main_15505_label :Read$/m);
    assert.match(items, new RegExp(`^experimental :menu_main_15505_icon :/mnt/onboard/${NM_MENU_ICON_CUSTOM_PNG_PATH}$`, 'm'));
    assert.deepEqual(device.writeFor(NM_MENU_ICON_CUSTOM_PNG_PATH).data, png);
    const manifest = JSON.parse(text(device.writeFor('.kobopatch-webui/nickelmenu.json').data));
    assert.deepEqual(manifest.configuration.menu, {
        label: 'Read',
        icon: {
            mimeType: 'image/png',
            data: btoa('png data'),
        },
    });
});

test('installToDevice uses the calibre sync exclusion when exclude-calibre is selected', async () => {
    const installer = createInstaller();
    const device = new RecordingDevice();

    await installer.installToDevice(device, [excludeCalibre], createProgressRecorder());

    assert.deepEqual(device.writePaths(), [koboEReaderConfPath, '.kobopatch-webui/nickelmenu.json', koboRootTgzPath]);
    assert.match(text(device.writeFor(koboEReaderConfPath).data), /^ExcludeSyncFolders=\(calibre\|/m);
});

// The bar must never claim a file is on the device before its write returns, and
// the fraction is what actually moves the bar — assert it, not just the text.
test('installToDevice reports a written file only once its write has returned', async () => {
    const installer = createInstaller();
    const device = new RecordingDevice({ textFiles: { [koboEReaderConfPath]: '' } });
    const feature = {
        id: 'three-files',
        title: 'Three files',
        analyticsEvent: null,
        install: () => [
            { path: 'a/one', data: '1' },
            { path: 'a/two', data: '2' },
            { path: 'a/three', data: '3' },
        ],
    };

    // Snapshot how many files had actually reached the device at each report.
    const observed = [];
    const progress = (message, detail, fraction) => observed.push({ message, detail, fraction, written: device.writes.length });

    await installer.installToDevice(device, [feature], progress);

    const writes = observed.filter((entry) => entry.message === 'Writing files to your Kobo...');
    // The conf file is written before the loop, so subtract it to count ours.
    assert.deepEqual(
        writes.map((entry) => [entry.detail, entry.fraction, entry.written - 1]),
        [
            ['1 of 3 files', 1 / 3, 1],
            ['2 of 3 files', 2 / 3, 2],
            ['3 of 3 files', 1, 3],
        ],
    );
});

test('buildDownloadZip reports compression progress with a fraction', async () => {
    const installer = createInstaller();
    const feature = { id: 'one-file', title: 'One file', analyticsEvent: null, install: () => [{ path: 'a/one', data: '1' }] };
    const observed = [];
    const progress = (message, detail, fraction) => observed.push({ message, detail, fraction });

    await installer.buildDownloadZip([feature], progress);

    const compressing = observed.filter((entry) => entry.message === 'Compressing...' && entry.fraction !== null && entry.fraction !== undefined);
    assert.ok(compressing.length > 0, 'compression should report a fraction, otherwise the bar never appears');
    assert.equal(compressing.at(-1).fraction, 1);
    assert.equal(compressing.at(-1).detail, '100%');
});

test('installToDevice writes post-processed NickelMenu items as bytes', async () => {
    const restoreFetch = useCustomMenuAssetFetch();
    const installer = createInstaller();
    const device = new RecordingDevice();

    try {
        await installer.installToDevice(device, [customMenu, hideNotices], createProgressRecorder());
    } finally {
        restoreFetch();
    }

    const itemsWrite = device.writeFor(NM_ITEMS_FILE);
    assert.ok(itemsWrite.data instanceof Uint8Array);
    const items = text(itemsWrite.data);
    // hide-notices contributes the shared home-content toggle item to the items file...
    assert.match(items, /toggle_hidden_home\.sh/);
    // ...and writes its hide flag to NickelHome's own config.
    const homeCfg = text(device.writeFor(NICKELHOME_CONFIG_FILE).data);
    assert.match(homeCfg, /hide_home_row3_enabled:1\n$/);
});

test('installToDevice de-duplicates the shared home-content toggle across hiders', async () => {
    const restoreFetch = useCustomMenuAssetFetch();
    const installer = createInstaller();
    const device = new RecordingDevice();
    const hiders = homeHiders.filter((f) => ['hide-recommendations', 'hide-notices'].includes(f.id));

    try {
        await installer.installToDevice(device, [customMenu, ...hiders], createProgressRecorder());
    } finally {
        restoreFetch();
    }

    // Two hiders each ship + contribute the same toggle, but it lands once.
    const scriptWrites = device.writePaths().filter((path) => path.endsWith('toggle_hidden_home.sh'));
    assert.deepEqual(scriptWrites, ['.adds/nm/scripts/toggle_hidden_home.sh']);

    const items = text(device.writeFor(NM_ITEMS_FILE).data);
    const toggleCount = (items.match(/Minimal Home/g) || []).length;
    assert.equal(toggleCount, 1);
    // Both hiders' distinct flags land in the single NickelHome config.
    const homeCfg = text(device.writeFor(NICKELHOME_CONFIG_FILE).data);
    assert.match(homeCfg, /hide_home_row1col2_enabled:1/);
    assert.match(homeCfg, /hide_home_row3_enabled:1/);
});

test('install fetches the shared home-content toggle script only once across hiders', async () => {
    const originalFetch = globalThis.fetch;
    const assets = {
        [CUSTOM_MENU_ICON_URL]: 'cog png',
        [TOGGLE_SCREENSHOTS_SCRIPT_URL]: '#!/bin/sh\nreport screenshot state',
        [TOGGLE_HIDDEN_HOME_SCRIPT_URL]: '#!/bin/sh\ntoggle home',
    };
    const fetchCounts = new Map();
    globalThis.fetch = async (url) => {
        fetchCounts.set(url, (fetchCounts.get(url) || 0) + 1);
        if (!(url in assets)) return { ok: false, status: 404 };
        return {
            ok: true,
            status: 200,
            async arrayBuffer() {
                const data = bytes(assets[url]);
                return data.buffer.slice(data.byteOffset, data.byteOffset + data.byteLength);
            },
        };
    };

    const installer = createInstaller();
    const device = new RecordingDevice();
    try {
        // All three hiders selected — each ships the same toggle script.
        await installer.installToDevice(device, [customMenu, ...homeHiders], createProgressRecorder());
    } finally {
        globalThis.fetch = originalFetch;
    }

    // The per-run asset cache collapses the three identical fetches into one.
    assert.equal(fetchCounts.get(TOGGLE_HIDDEN_HOME_SCRIPT_URL), 1);
    // ...and the script is still written exactly once.
    const scriptWrites = device.writePaths().filter((path) => path.endsWith('toggle_hidden_home.sh'));
    assert.deepEqual(scriptWrites, ['.adds/nm/scripts/toggle_hidden_home.sh']);
});

test('installToDevice writes an audit log under .kobopatch-webui/logs when an AuditLog is passed', async () => {
    const restoreFetch = useCustomMenuAssetFetch();
    const installer = createInstaller();
    const device = new RecordingDevice();
    const audit = new AuditLog('install-nickelmenu', new Date(2026, 5, 11, 14, 30));

    try {
        await installer.installToDevice(device, [customMenu], createProgressRecorder(), { audit });
    } finally {
        restoreFetch();
    }

    const logPath = '.kobopatch-webui/logs/26-06-11_14-30-install-nickelmenu.log';
    assert.ok(device.writePaths().includes(logPath));
    const log = text(device.writeFor(logPath).data);
    assert.match(log, /wrote \.kobo\/KoboRoot\.tgz/);
    assert.match(log, /Set Kobo eReader\.conf ExcludeSyncFolders=/);
    assert.match(log, /Wrote \.adds\/nm\/webui-preset/);
});

test('installToDevice writes manifest but no audit log when none is passed', async () => {
    const restoreFetch = useCustomMenuAssetFetch();
    const installer = createInstaller();
    const device = new RecordingDevice();

    try {
        await installer.installToDevice(device, [customMenu], createProgressRecorder());
    } finally {
        restoreFetch();
    }

    // Manifest is always written; no audit log file should exist.
    assert.ok(device.writePaths().includes('.kobopatch-webui/nickelmenu.json'));
    assert.ok(!device.writePaths().some((path) => path.startsWith('.kobopatch-webui/logs/')));
});

test('installToDevice stops after preceding writes if final KoboRoot.tgz write fails', async () => {
    const installer = createInstaller();
    const device = new RecordingDevice({ failWritePath: koboRootTgzPath });

    await assert.rejects(() => installer.installToDevice(device, [excludeCalibre], createProgressRecorder()), /Refusing write to \.kobo\/KoboRoot\.tgz/);
    assert.deepEqual(device.writePaths(), [koboEReaderConfPath, '.kobopatch-webui/nickelmenu.json']);
});

test('installToDevice stops before config overwrite when Kobo eReader.conf cannot be read', async () => {
    const installer = createInstaller();
    const device = new RecordingDevice({
        textFiles: {
            [koboEReaderConfPath]: '[General]\nsome=setting\n',
        },
        failReadPaths: [koboEReaderConfPath],
    });

    await assert.rejects(
        () => installer.installToDevice(device, [excludeCalibre], createProgressRecorder()),
        /Refusing read of \.kobo\/Kobo\/Kobo eReader\.conf/,
    );
    assert.deepEqual(device.writePaths(), []);
    assert.equal(device.writeFor(koboEReaderConfPath), undefined);
});

test('installToDevice stops writing remaining feature files after a feature write fails', async () => {
    const restoreFetch = useCustomMenuAssetFetch();
    const installer = createInstaller();
    const device = new RecordingDevice({ failWritePath: '.adds/nm/.cog.png' });

    try {
        await assert.rejects(() => installer.installToDevice(device, [customMenu], createProgressRecorder()), /Refusing write to \.adds\/nm\/\.cog\.png/);
    } finally {
        restoreFetch();
    }
    assert.deepEqual(device.writePaths(), [koboEReaderConfPath]);
});

test('installToDevice does not write to the device when NickelMenu fails to load', async () => {
    const installer = new NickelMenuInstaller();
    installer.loadNickelMenu = async () => {
        throw new Error('Failed to download NickelMenu');
    };
    const device = new RecordingDevice();

    await assert.rejects(() => installer.installToDevice(device, [], createProgressRecorder()), /Failed to download NickelMenu/);
    assert.deepEqual(device.writePaths(), []);
});

test('buildDownloadZip with no features includes NickelMenu KoboRoot.tgz and manifest', async () => {
    const tgz = bytes('download tgz');
    const installer = createInstaller(tgz);

    const result = await installer.buildDownloadZip([], createProgressRecorder());
    const zip = await JSZip.loadAsync(result);
    const filePaths = Object.keys(zip.files).filter((path) => !zip.files[path].dir);

    assert.deepEqual(filePaths, ['.kobo/KoboRoot.tgz', '.kobopatch-webui/nickelmenu.json', 'instructions.txt']);
    assert.deepEqual(await zip.file('.kobo/KoboRoot.tgz').async('uint8array'), tgz);

    const manifest = JSON.parse(await zip.file('.kobopatch-webui/nickelmenu.json').async('string'));
    assert.deepEqual(manifest.selected, []);

    // No preset chosen → no config steps, but the credit header and disclaimer
    // are always present.
    const instructions = await zip.file('instructions.txt').async('string');
    assert.match(instructions, /Generated by KoboPatch Web UI/);
    assert.match(instructions, /reset your Kobo/);
    assert.ok(!instructions.includes('Kobo eReader.conf'));
});

test('buildDownloadZip with features includes feature files but not Kobo eReader.conf', async () => {
    const restoreFetch = useCustomMenuAssetFetch();
    const installer = createInstaller(bytes('download tgz'));

    try {
        const result = await installer.buildDownloadZip([customMenu, hideNotices], createProgressRecorder());
        const zip = await JSZip.loadAsync(result);
        const filePaths = Object.keys(zip.files).filter((path) => !zip.files[path].dir);

        assert.deepEqual(filePaths, [
            '.kobo/KoboRoot.tgz',
            '.adds/nm/.cog.png',
            '.adds/nm/scripts/toggle_screenshots.sh',
            '.adds/nm/scripts/toggle_hidden_home.sh',
            NM_ITEMS_FILE,
            NICKELHOME_CONFIG_FILE,
            '.kobopatch-webui/nickelmenu.json',
            'instructions.txt',
        ]);
        assert.match(await zip.file(NICKELHOME_CONFIG_FILE).async('string'), /hide_home_row3_enabled:1\n$/);
        assert.equal(zip.file(koboEReaderConfPath), null);

        // A preset install (features present) gets the ExcludeSyncFolders
        // config step in its bundled instructions.
        const instructions = await zip.file('instructions.txt').async('string');
        assert.match(instructions, /Kobo eReader\.conf/);
        assert.match(instructions, /ExcludeSyncFolders=/);
    } finally {
        restoreFetch();
    }
});

test('buildDownloadZip rejects when NickelMenu fails to load', async () => {
    const installer = new NickelMenuInstaller();
    installer.loadNickelMenu = async () => {
        throw new Error('Failed to download NickelMenu');
    };

    await assert.rejects(() => installer.buildDownloadZip([], createProgressRecorder()), /Failed to download NickelMenu/);
});

// --- KoboRoot.tgz merging (the generic koboRootEntries hook) ---

const nmTgzEntry = { path: 'usr/local/Kobo/imageformats/libnm.so', data: bytes('nm plugin'), mode: 0o755 };

// A feature that contributes its own KoboRoot.tgz payload, like NickelClock.
const tgzAddonFeature = {
    id: 'tgz-addon',
    title: 'Tgz Addon',
    async koboRootEntries() {
        return [
            { path: 'usr/local/Kobo/imageformats/libaddon.so', data: bytes('addon plugin'), mode: 0o755 },
            { path: 'mnt/onboard/.adds/addon/uninstall', data: bytes('marker'), mode: 0o644 },
        ];
    },
};

async function createInstallerWithBaseTgz() {
    const installer = new NickelMenuInstaller();
    installer.nickelMenuTgz = await buildTarGz([nmTgzEntry]);
    return installer;
}

test('buildKoboRootTgz returns the base tgz verbatim when no feature contributes entries', async () => {
    const tgz = bytes('opaque base tgz');
    const installer = createInstaller(tgz);

    const result = await installer.buildKoboRootTgz([excludeCalibre], createProgressRecorder());
    assert.deepEqual(result, tgz);
});

test('buildKoboRootTgz merges a feature koboRootEntries payload into one archive', async () => {
    const installer = await createInstallerWithBaseTgz();

    const merged = await installer.buildKoboRootTgz([tgzAddonFeature], createProgressRecorder());
    const entries = await parseTarGz(merged);

    assert.deepEqual(
        entries.map((e) => e.path),
        ['usr/local/Kobo/imageformats/libnm.so', 'usr/local/Kobo/imageformats/libaddon.so', 'mnt/onboard/.adds/addon/uninstall'],
    );
    // Executable bits on both plugins are preserved through the rebuild.
    assert.equal(entries.find((e) => e.path.endsWith('libnm.so')).mode, 0o755);
    assert.equal(entries.find((e) => e.path.endsWith('libaddon.so')).mode, 0o755);
    assert.deepEqual(entries.find((e) => e.path.endsWith('uninstall')).data, bytes('marker'));
});

test('installToDevice writes the merged KoboRoot.tgz when a tgz-addon feature is selected', async () => {
    const installer = await createInstallerWithBaseTgz();
    const device = new RecordingDevice();

    await installer.installToDevice(device, [tgzAddonFeature], createProgressRecorder());

    const written = device.writeFor(koboRootTgzPath);
    const entries = await parseTarGz(written.data);
    assert.ok(entries.some((e) => e.path.endsWith('libnm.so')));
    assert.ok(entries.some((e) => e.path.endsWith('libaddon.so')));
});

// --- collectFiles: the file-assembly core, driven directly with fake features ---

test('collectFiles with zero features produces no files and an empty manifest map', async () => {
    const installer = new NickelMenuInstaller();

    const { files, featureFiles } = await installer.collectFiles([], () => {});

    assert.deepEqual(files, []);
    assert.deepEqual(featureFiles, {});
});

test('collectFiles keeps the first write when two features ship the same path', async () => {
    const installer = new NickelMenuInstaller();
    // Same path, different bytes: dedup must keep the FIRST feature's file, not
    // the second (an identical-content test could not tell the two apart).
    const first = { id: 'first', title: 'First', install: () => [{ path: 'shared/file', data: 'from-first' }] };
    const second = { id: 'second', title: 'Second', install: () => [{ path: 'shared/file', data: 'from-second' }] };

    const { files, featureFiles } = await installer.collectFiles([first, second], () => {});

    const shared = files.filter((f) => f.path === 'shared/file');
    assert.equal(shared.length, 1);
    assert.equal(shared[0].data, 'from-first');
    // The manifest attributes the shared path to both features that shipped it,
    // even though only the first write survives (each owns it for uninstall).
    assert.deepEqual(featureFiles.first, ['shared/file']);
    assert.deepEqual(featureFiles.second, ['shared/file']);
});

test('collectFiles records an empty file list for a feature whose install returns []', async () => {
    const installer = new NickelMenuInstaller();
    const feature = { id: 'noop', title: 'Noop', install: () => [] };

    const { files, featureFiles } = await installer.collectFiles([feature], () => {});

    assert.deepEqual(files, []);
    assert.deepEqual(featureFiles, { noop: [] });
});

test('collectFiles preserves both string and Uint8Array install data', async () => {
    const installer = new NickelMenuInstaller();
    const feature = {
        id: 'mixed',
        title: 'Mixed',
        install: () => [
            { path: 'as-string', data: 'plain text' },
            { path: 'as-bytes', data: bytes('raw bytes') },
        ],
    };

    const { files } = await installer.collectFiles([feature], () => {});

    const asString = files.find((f) => f.path === 'as-string');
    const asBytes = files.find((f) => f.path === 'as-bytes');
    assert.equal(typeof asString.data, 'string');
    assert.equal(asString.data, 'plain text');
    assert.ok(asBytes.data instanceof Uint8Array);
    assert.equal(text(asBytes.data), 'raw bytes');
});

test('collectFiles encodes the generated items file to bytes', async () => {
    const installer = new NickelMenuInstaller();
    const feature = { id: 'menuonly', title: 'Menu Only', menuItems: () => [{ id: 'screenshots', lines: ['menu_item :main :Screenshots'] }] };

    const { files } = await installer.collectFiles([feature], () => {});

    const items = files.find((f) => f.path === NM_ITEMS_FILE);
    assert.ok(items.data instanceof Uint8Array);
    assert.match(text(items.data), /^# Generated by KoboPatch Web UI/);
    assert.match(text(items.data), /menu_item :main :Screenshots/);
});

test('collectFiles runs postProcess in order so two features append to one shared file', async () => {
    const installer = new NickelMenuInstaller();
    // find-or-create: the first postProcess creates the file, the second must
    // see it and append rather than overwrite. Second sees the first's mutation.
    const appendLine = (line) => (files) => {
        let cfg = files.find((f) => f.path === 'shared/log');
        if (!cfg) {
            cfg = { path: 'shared/log', data: 'HEADER\n' };
            files.push(cfg);
        }
        cfg.data += line + '\n';
        return files;
    };
    const a = { id: 'a', title: 'A', postProcess: appendLine('line-a') };
    const b = { id: 'b', title: 'B', postProcess: appendLine('line-b') };

    const { files } = await installer.collectFiles([a, b], () => {});

    const log = files.filter((f) => f.path === 'shared/log');
    assert.equal(log.length, 1);
    assert.equal(log[0].data, 'HEADER\nline-a\nline-b\n');
});

test('collectFiles de-duplicates a shared path across a large number of features', async () => {
    const installer = new NickelMenuInstaller();
    const features = Array.from({ length: 500 }, (_, i) => ({
        id: `f${i}`,
        title: `F${i}`,
        install: () => [{ path: 'shared/asset', data: `data-${i}` }],
    }));

    const { files, featureFiles } = await installer.collectFiles(features, () => {});

    const shared = files.filter((f) => f.path === 'shared/asset');
    assert.equal(shared.length, 1);
    assert.equal(shared[0].data, 'data-0');
    assert.equal(Object.keys(featureFiles).length, 500);
});

test('installToDevice writes the items file as bytes even when a postProcess replaces the file objects', async () => {
    const installer = createInstaller();
    const device = new RecordingDevice();
    const menu = { id: 'menu', title: 'Menu', menuItems: () => [{ id: 'screenshots', lines: ['menu_item :main :Screenshots'] }] };
    // A postProcess that returns freshly-cloned objects (rather than mutating in
    // place) invalidates any reference captured before it ran. The file written
    // to the device must still be correctly byte-encoded.
    const cloner = { id: 'cloner', title: 'Cloner', postProcess: (files) => files.map((f) => ({ ...f })) };

    await installer.installToDevice(device, [menu, cloner], createProgressRecorder());

    const items = device.writeFor(NM_ITEMS_FILE);
    assert.ok(items.data instanceof Uint8Array);
    assert.match(text(items.data), /menu_item :main :Screenshots/);
});

// --- buildKoboRootTgz: keep-first merge semantics ---

test('buildKoboRootTgz keeps the base entry when a feature duplicates its path', async () => {
    const installer = new NickelMenuInstaller();
    installer.nickelMenuTgz = await buildTarGz([{ path: 'shared/plugin.so', data: bytes('base bytes'), mode: 0o644 }]);
    const baseBefore = installer.nickelMenuTgz.slice();
    const feature = {
        id: 'dup',
        title: 'Dup',
        koboRootEntries: () => [
            { path: 'shared/plugin.so', data: bytes('feature bytes'), mode: 0o755 },
            { path: 'feature/only', data: bytes('new'), mode: 0o644 },
        ],
    };

    const merged = await installer.buildKoboRootTgz([feature], () => {});
    const entries = await parseTarGz(merged);

    const shared = entries.find((e) => e.path === 'shared/plugin.so');
    // Base occurs first in the merge, so the base bytes and mode win.
    assert.equal(text(shared.data), 'base bytes');
    assert.equal(shared.mode, 0o644);
    assert.ok(entries.some((e) => e.path === 'feature/only'));
    // The base archive bytes must not be mutated by the merge.
    assert.deepEqual(installer.nickelMenuTgz, baseBefore);
});

test('buildKoboRootTgz keeps the first feature entry when two features ship the same path', async () => {
    const installer = new NickelMenuInstaller();
    installer.nickelMenuTgz = await buildTarGz([{ path: 'base/x', data: bytes('base'), mode: 0o644 }]);
    const first = { id: 'first', title: 'First', koboRootEntries: () => [{ path: 'clash', data: bytes('first'), mode: 0o644 }] };
    const second = { id: 'second', title: 'Second', koboRootEntries: () => [{ path: 'clash', data: bytes('second'), mode: 0o644 }] };

    const merged = await installer.buildKoboRootTgz([first, second], () => {});
    const entries = await parseTarGz(merged);

    assert.equal(text(entries.find((e) => e.path === 'clash').data), 'first');
});

test('buildKoboRootTgz returns the base tgz verbatim when a feature contributes an empty entry list', async () => {
    const base = bytes('opaque base tgz');
    const installer = createInstaller(base);
    // Distinct from the no-hook case: this feature HAS koboRootEntries, but it
    // returns [] — the merge must still short-circuit to the untouched base.
    const feature = { id: 'empty', title: 'Empty', koboRootEntries: () => [] };

    const result = await installer.buildKoboRootTgz([feature], () => {});

    assert.equal(result, base);
});

// --- buildManifest: per-feature entry shapes ---

test('buildManifest records files, directories, conf, and menuItems-only features', async () => {
    const installer = new NickelMenuInstaller();
    const withFiles = { id: 'with-files', title: 'With Files', install: () => [{ path: 'f1', data: 'x' }] };
    const menuOnly = { id: 'menu-only', title: 'Menu Only', menuItems: () => [] };
    const withDirs = { id: 'with-dirs', title: 'With Dirs', directories: [['adds', 'thing']] };
    const withConf = {
        id: 'with-conf',
        title: 'With Conf',
        confSettings: () => [{ section: 'S', key: 'k', value: 'v', revertable: true, revertTo: 'old' }],
    };
    const features = [withFiles, menuOnly, withDirs, withConf];

    const { files, featureFiles } = await installer.collectFiles(features, () => {});
    const manifest = installer.buildManifest(features, files, featureFiles, null, null);

    assert.deepEqual(manifest.selected, ['with-files', 'menu-only', 'with-dirs', 'with-conf']);
    assert.deepEqual(manifest.features['with-files'].files, [{ path: 'f1', type: 'file' }]);
    // A feature that only contributes menu items owns no files of its own.
    assert.deepEqual(manifest.features['menu-only'].files, []);
    // directories short-circuit the files list entirely.
    assert.deepEqual(manifest.features['with-dirs'].directories, [['adds', 'thing']]);
    assert.equal(manifest.features['with-dirs'].files, undefined);
    // Only revertable conf settings are recorded, with revertTo carried through.
    assert.deepEqual(manifest.features['with-conf'].conf, [{ section: 'S', key: 'k', value: 'v', revertTo: 'old' }]);
});
